const APP_MODE=window.SALON_MODE||"customer";

const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=i=>document.getElementById(i),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fm=n=>Math.round(n).toLocaleString("ar-EG")+" "+C.cfg.currency;
const toast=t=>{const e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)};
const ST={upcoming:"قادم",checked_in:"وصل",in_service:"على الكرسي",done:"خلص",cancelled:"ملغي"};
let me=null,tab="";const C={cfg:{salon_name:"صالون أبو يوسف",phone:"",address:"",currency:"ج.م",open_hour:10,close_hour:20,slot_minutes:60,days_ahead:5,weekly_off:5,cancel_before_hours:2,points_per_currency:10,max_discount_pct:20,booking_open:true}};

const PD={cashier:{use_attendance:1,use_pos:1,view_stock:1,view_invoices:1,manage_appts:1,view_customers:1,view_customer_phone:1},barber:{use_attendance:1,view_own_sales:1,view_own_commission:1,view_own_finance:1,view_own_reviews:1,view_own_schedule:1},assistant:{use_attendance:1,view_own_finance:1}};
const can=(k,p=me)=>p.role=="owner"||(p.perms&&k in p.perms?!!p.perms[k]:!!(PD[p.role]||{})[k]);
async function loadCfg(){const{data}=await sb.from("app_settings").select("*");(data||[]).forEach(r=>C.cfg[r.key]=r.value);document.title=C.cfg.salon_name;$("brand").innerHTML=ic("menu")+"<span>"+esc(C.cfg.salon_name)+(APP_MODE=="staff"?" · الموظفين":"")+"</span>"}
async function boot(){
await loadCfg();
const{data:{session}}=await sb.auth.getSession();
if(!session){let cr=null;try{cr=JSON.parse(localStorage.getItem("salon_cred"))}catch(e){}
if(cr&&APP_MODE=="customer"){const r=await sb.auth.signInWithPassword({email:cr.e,password:cr.p});if(!r.error)return boot()}
return authView()}
const{data:p}=await sb.from("profiles").select("*").eq("id",session.user.id).single();
me=p||{role:"customer",full_name:session.user.email,id:session.user.id};
const staff=["owner","cashier","barber","assistant"].includes(me.role);
if(APP_MODE=="customer"&&staff)return wrongPage("staff");if(APP_MODE=="staff"&&!staff)return wrongPage("customer");
const own=me.role=="owner";
if(staff){const T=[];if(can("use_pos"))T.push(["pos","الكاشير"]);if(can("manage_appts"))T.push(["appts","الحجوزات"]);if(can("view_stock"))T.push(["stock","المخزون"]);if(can("view_invoices"))T.push(["inv","الفواتير"]);if(can("view_customers"))T.push(["cust","العملاء"]);if(can("view_reports"))T.push(["rep","التقارير"]);if(me.role=="barber"||me.role=="assistant"||can("use_attendance"))T.push(["me","شاشتي"]);if(own)T.push(["team","الموظفين"],["set","الإعدادات"]);C.tabs=[...T,["out","خروج"]];go(T[0]?T[0][0]:"none")}
else{const{data:cu}=await sb.from("customers").select("id").eq("user_id",session.user.id).maybeSingle();if(!cu)return authView("c");C.tabs=[["book","احجز"],["queue","دوري"],["mine","حجوزاتي"],["loy","نقاطي"],["menu","المنيو"]];go("book")}}

function go(t){clearInterval(C.poll);if(t=="out"){sb.auth.signOut().then(()=>{$("nav").innerHTML="";authView()});return}
tab=t;$("app").classList.remove("still");$("nav").innerHTML=C.tabs.map(x=>`<button class="${x[0]==t?"on":""}" onclick="go('${x[0]}')">${ic(x[0])}<span>${x[1]}</span></button>`).join("");put(SK);scrollTo(0,0);V[t]()}
const put=h=>$("app").innerHTML=h;

function authView(){put(`<h1>أهلاً بيك في ${esc(C.cfg.salon_name)}</h1><div class="box"><input id="nm" placeholder="الاسم (للتسجيل الجديد فقط)"><input id="em" type="email" placeholder="البريد الإلكتروني"><input id="pw" type="password" placeholder="كلمة السر (6 حروف على الأقل)"><div class="chips"><button class="btn" onclick="login()">دخول</button><button class="btn g" onclick="signup()">حساب جديد</button></div></div>`)}
async function login(){const{error}=await sb.auth.signInWithPassword({email:$("em").value.trim(),password:$("pw").value});error?toast("بيانات الدخول غلط"):boot()}
async function signup(){const{error}=await sb.auth.signUp({email:$("em").value.trim(),password:$("pw").value,options:{data:{full_name:$("nm").value.trim()}}});if(error)return toast(error.message);toast("تم إنشاء الحساب");boot()}

const V={
// ===== عميل =====
async book(){
if(!C.cfg.booking_open)return put(`<h1>الحجز</h1><p class="m">الحجز أونلاين متوقف حاليًا. كلمنا على ${esc(C.cfg.phone||"الصالون")}.</p>`);
const[{data:sv},{data:br}]=await Promise.all([sb.from("services").select("*").eq("active",true).order("id"),sb.rpc("list_barbers")]);
C.sv=sv||[];C.br=br||[];C.b={s:[],barber:null,day:0,time:null};drawBook()},
async mine(){
const{data}=await sb.from("appointments").select("id,starts_at,status,appointment_services(services(name)),reviews:invoices(id,reviews(rating))").order("starts_at",{ascending:false});
put(`<h1>حجوزاتي</h1>`+(data?.length?data.map(a=>{const inv=a.reviews?.[0],rated=inv?.reviews?.length;return `<div class="row"><div><b>${new Date(a.starts_at).toLocaleString("ar-EG",{weekday:"long",hour:"2-digit",minute:"2-digit",day:"numeric",month:"numeric"})}</b><div class="m">${(a.appointment_services||[]).map(x=>x.services.name).join(" + ")}</div></div><div><span class="tag">${ST[a.status]}</span>${a.status=="done"&&inv&&!rated?`<br><button class="btn s" onclick="rateView(${inv.id})">قيّم</button>`:""}${rated?`<div class="m">★ ${inv.reviews[0].rating}</div>`:""}${a.status=="upcoming"?`<br><button class="btn s g" onclick="cancelA(${a.id})">إلغاء</button>`:""}</div></div>`}).join(""):`<p class="m">لسه معندكش حجوزات.</p>`))},
// ===== موظفين =====
async pos(){
const[{data:sv},{data:pr},{data:cu},{data:br},{data:asx}]=await Promise.all([sb.from("services").select("*").eq("active",true),sb.from("products").select("*").eq("active",true),sb.from("customers").select("id,name"),sb.from("profiles").select("id,full_name").eq("role","barber"),sb.from("profiles").select("id,full_name,commission_pct").eq("role","assistant")]);
C.P={sv,pr,cu,br,as:asx||[],sa:C.P?.sa||{},s:C.P?.s||[],p:C.P?.p||[],cid:C.P?.cid||"",bid:C.P?.bid||"",appt:C.P?.appt||null,disc:0,pay:"cash"};drawPos();if(C.P.cid)loadV()},
async appts(){
const from=new Date();from.setHours(0,0,0,0);
const{data}=await sb.from("appointments").select("id,starts_at,status,customer_id,barber_id,customers(name),profiles(full_name),appointment_services(service_id,services(name))").gte("starts_at",from.toISOString()).order("starts_at");
C.A=data||[];put(`<h1>الحجوزات</h1>`+(C.A.length?C.A.map(a=>`<div class="row"><div><b>${new Date(a.starts_at).toLocaleString("ar-EG",{weekday:"short",hour:"2-digit",minute:"2-digit"})}</b> · ${esc(a.customers?.name)}<div class="m">${a.appointment_services.map(x=>esc(x.services.name)).join(" + ")} · ${esc(a.profiles?.full_name||"أي حلاق")}</div></div><div style="text-align:left"><span class="tag">${ST[a.status]}</span><br>${a.status=="upcoming"?`<button class="btn s" onclick="setS(${a.id},'checked_in')">وصل</button> <button class="btn s g" onclick="setS(${a.id},'cancelled')">إلغاء</button>`:""}${a.status=="checked_in"?`<button class="btn s" onclick="setS(${a.id},'in_service')">ابدأ</button>`:""}${a.status=="in_service"?`<button class="btn s" onclick="payAppt(${a.id})">دفع</button>`:""}</div></div>`).join(""):`<p class="m">مفيش حجوزات قادمة.</p>`))},
async stock(){
const{data}=await sb.from("products").select("*").order("name");
put(`<h1>المخزون</h1>`+data.map(p=>`<div class="row"><div><b>${esc(p.name)}</b><div class="m">شراء ${p.cost} · بيع ${p.price}</div></div><div style="text-align:left"><span class="tag" style="${p.stock<=p.min_stock?"background:var(--red);color:#fff":""}">${p.stock} قطعة</span><br>${can("restock")?`<button class="btn s g" onclick="restock(${p.id},${p.stock})">+10 توريد</button>`:""}</div></div>`).join(""))},
async inv(){
const{data,error}=await sb.from("invoices").select("no,total,payment_method,created_at,customers(name),invoice_items(name,qty,unit_price)").order("created_at",{ascending:false}).limit(50);
if(error)return put(`<h1>الفواتير</h1><p class="m">مفيش صلاحية لعرض الفواتير لحسابك.</p>`);
put(`<h1>الفواتير</h1>`+(data.length?data.map(i=>`<details class="row" style="display:block"><summary><b>#${i.no}</b> · ${esc(i.customers?.name||"عميل عابر")} · <b>${fm(i.total)}</b></summary>${i.invoice_items.map(x=>`<div class="tot m"><span>${esc(x.name)} ×${x.qty}</span><span>${fm(x.unit_price*x.qty)}</span></div>`).join("")}<div class="m">${new Date(i.created_at).toLocaleString("ar-EG")} · ${i.payment_method}</div></details>`).join(""):`<p class="m">لسه مفيش فواتير.</p>`))}
};

function drawBook(){const b=C.b,days=[...Array(+C.cfg.days_ahead)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return{i,off:d.getDay()==C.cfg.weekly_off,l:i?d.toLocaleDateString("ar-EG",{weekday:"short",day:"numeric",month:"numeric"}):"اليوم"}});
const times=slots();
put(`<h1>احجز موعد</h1><h2>الخدمات</h2><div class="chips">${C.sv.map(s=>`<button class="chip ${b.s.includes(s.id)?"sel":""}" onclick="tgS(${s.id})">${esc(s.name)} · ${s.price}</button>`).join("")}</div>
<h2>الحلاق</h2><div class="chips"><button class="chip ${b.barber===null?"sel":""}" onclick="C.b.barber=null;bookSlots()">أي حلاق</button>${C.br.map(x=>`<button class="chip ${b.barber===x.id?"sel":""}" onclick="C.b.barber='${x.id}';bookSlots()">${esc(x.full_name)}</button>`).join("")}</div>
<h2>اليوم</h2><div class="chips">${days.map(d=>`<button class="chip ${b.day==d.i?"sel":""}" ${d.off?"disabled":""} onclick="C.b.day=${d.i};C.b.time=null;bookSlots()">${d.l}</button>`).join("")}</div>
<h2>الساعة</h2><div class="chips" id="slots"></div>
<button class="btn" style="width:100%;margin-top:10px" ${b.s.length&&b.time!=null?"":"disabled"} onclick="confirmBook()">تأكيد الحجز · ${fm(C.sv.filter(s=>b.s.includes(s.id)).reduce((a,s)=>a+s.price,0))}</button>`);
bookSlots()}
async function bookSlots(){const b=C.b;const d=new Date();d.setDate(d.getDate()+b.day);const ds=d.toISOString().slice(0,10);
const[{data},{data:bh}]=await Promise.all([sb.rpc("taken_slots",{p_day:ds}),sb.rpc("barber_hours",{p_day:ds})]);const times=slots();const okB=(bid,t)=>{const h=(bh||[]).find(x=>x.barber_id==bid);return !h||(!h.is_off&&t+":00">=h.start_time&&t+":00"<h.end_time)};
const mk=t=>{const x=new Date(d);const[h,m]=t.split(":");x.setHours(+h,+m,0,0);return x};
const taken=t=>{const iso=mk(t).getTime(),bt=r=>new Date(r.starts_at).getTime()==iso;if(b.barber)return !okB(b.barber,t)||(data||[]).some(r=>bt(r)&&r.barber_id==b.barber);return C.br.length>0&&!C.br.some(x=>okB(x.id,t)&&!(data||[]).some(r=>bt(r)&&r.barber_id==x.id))};
const past=t=>mk(t)<new Date();
if($("slots"))$("slots").innerHTML=times.map(t=>`<button class="chip ${b.time===t?"sel":""}" ${taken(t)||past(t)?"disabled":""} onclick="C.b.time='${t}';drawBook()">${t}</button>`).join("");
document.querySelector(".btn[onclick='confirmBook()']")&&(document.querySelector(".btn[onclick='confirmBook()']").disabled=!(b.s.length&&b.time))}
function tgS(id){const b=C.b;b.s=b.s.includes(id)?b.s.filter(x=>x!=id):[...b.s,id];drawBook()}
async function confirmBook(){const b=C.b;const{data:{user}}=await sb.auth.getUser();
let{data:cu}=await sb.from("customers").select("id").eq("user_id",user.id).maybeSingle();
if(!cu){const r=await sb.from("customers").insert({user_id:user.id,name:me.full_name}).select("id").single();cu=r.data}
const d=new Date();d.setDate(d.getDate()+b.day);const[h,m]=b.time.split(":");d.setHours(+h,+m,0,0);
const{data:a,error}=await sb.from("appointments").insert({customer_id:cu.id,barber_id:b.barber,starts_at:d.toISOString()}).select("id").single();
if(error)return toast(error.code=="23505"?"الميعاد ده اتحجز، اختار وقت تاني":error.message);
await sb.from("appointment_services").insert(b.s.map(s=>({appointment_id:a.id,service_id:s})));
toast("تم تأكيد حجزك ✓");go("mine")}
async function cancelA(id){const{error}=await sb.rpc("cancel_my_appt",{p_id:id});error?toast(error.message):go("mine")}
const slots=()=>{const o=[],st=+C.cfg.slot_minutes;for(let m=C.cfg.open_hour*60;m+st<=C.cfg.close_hour*60;m+=st)o.push(String(m/60|0).padStart(2,"0")+":"+String(m%60).padStart(2,"0"));return o};
function rateView(inv){C.R={inv,r:0,tg:[]};drawRate()}
function drawRate(){const R=C.R,tags=["نظافة المكان","دقة الموعد","مهارة الحلاق","سعر مناسب"];
put(`<h1>قيّم تجربتك</h1><div class="stars" style="text-align:center">${[1,2,3,4,5].map(i=>`<button class="${R.r>=i?"on":""}" aria-label="${i}" onclick="C.R.r=${i};drawRate()">★</button>`).join("")}</div><div class="chips">${tags.map(t=>`<button class="chip ${R.tg.includes(t)?"sel":""}" onclick="C.R.tg=C.R.tg.includes('${t}')?C.R.tg.filter(x=>x!='${t}'):[...C.R.tg,'${t}'];drawRate()">${t}</button>`).join("")}</div><input id="nt" placeholder="ملاحظات (اختياري)"><button class="btn" ${R.r?"":"disabled"} onclick="sendRate()">إرسال</button>`)}
async function sendRate(){const R=C.R;const{data:{user}}=await sb.auth.getUser();
const{data:cu}=await sb.from("customers").select("id").eq("user_id",user.id).single();
const{data:inv}=await sb.from("invoices").select("barber_id").eq("id",R.inv).single();
const{error}=await sb.from("reviews").insert({invoice_id:R.inv,customer_id:cu.id,barber_id:inv?.barber_id,rating:R.r,tags:R.tg,note:$("nt").value});
error?toast(error.message):(toast("شكرًا على تقييمك 💈"),go("mine"))}

// ===== كاشير =====
function drawPos(){const P=C.P,sub=P.s.reduce((a,i)=>a+P.sv.find(x=>x.id==i).price,0)+P.p.reduce((a,i)=>a+P.pr.find(x=>x.id==i.id).price*i.q,0),d=sub*P.disc/100;
put(`<h1>الكاشير</h1><h2>الخدمات</h2><div class="chips">${P.sv.map(x=>`<button class="chip ${P.s.includes(x.id)?"sel":""}" onclick="P_s(${x.id})">${esc(x.name)} · ${x.price}</button>`).join("")}</div><h2>المنتجات</h2><div class="chips">${P.pr.map(x=>{const c=P.p.find(y=>y.id==x.id);return `<button class="chip ${c?"sel":""}" ${x.stock<=0?"disabled":""} onclick="P_p(${x.id})">${esc(x.name)} · ${x.price}${c?" ×"+c.q:""}</button>`}).join("")}</div>
<div class="box" style="margin-top:12px"><select onchange="C.P.cid=this.value;loadV()"><option value="">عميل عابر</option>${P.cu.map(c=>`<option value="${c.id}" ${P.cid==c.id?"selected":""}>${esc(c.name)}</option>`).join("")}</select>${P.vs?.length?`<select onchange="C.P.rid=this.value"><option value="">بدون كوبون ولاء</option>${P.vs.map(v=>`<option value="${v.id}" ${P.rid==v.id?"selected":""}>${esc(v.loyalty_rewards.name)} (${v.code})</option>`).join("")}</select>`:""}<select onchange="C.P.bid=this.value"><option value="">اختار الحلاق</option>${P.br.map(c=>`<option value="${c.id}" ${P.bid==c.id?"selected":""}>${esc(c.full_name)}</option>`).join("")}</select>
<div class="chips">${[0,5,10,20].filter(x=>me.role=="owner"||x<=C.cfg.max_discount_pct).map(x=>`<button class="chip ${P.disc==x?"sel":""}" onclick="C.P.disc=${x};drawPos()">خصم ${x}%</button>`).join("")}${[["cash","كاش"],["card","كارت"],["wallet","محفظة"]].map(x=>`<button class="chip ${P.pay==x[0]?"sel":""}" onclick="C.P.pay='${x[0]}';drawPos()">${x[1]}</button>`).join("")}</div>
${P.as.length&&P.s.length?`<h2>المساعد (اختياري)</h2><div class="box">${P.s.map(id=>{const v=P.sv.find(x=>x.id==id);return `<div class="m" style="margin-top:6px">${esc(v.name)}</div><select onchange="P_a(${id},this.value)"><option value="">بدون مساعد</option>${P.as.map(a=>`<option value="${a.id}" ${P.sa[id]==a.id?"selected":""}>${esc(a.full_name)} (${+a.commission_pct}%)</option>`).join("")}</select>`}).join("")}</div>`:""}
<div class="tot f"><span>المطلوب</span><span>${fm(sub-d)}</span></div><button class="btn" style="width:100%;margin-top:8px" ${sub?"":"disabled"} onclick="checkout()">دفع وإصدار فاتورة</button></div>`)}
function P_s(id){const P=C.P;if(P.s.includes(id))delete P.sa[id];P.s=P.s.includes(id)?P.s.filter(x=>x!=id):[...P.s,id];drawPos()}
function P_a(id,v){if(v)C.P.sa[id]=v;else delete C.P.sa[id]}
function P_p(id){const P=C.P,c=P.p.find(x=>x.id==id),pr=P.pr.find(x=>x.id==id);if(c){c.q<pr.stock?c.q++:toast("الكمية خلصت")}else P.p.push({id,q:1});drawPos()}
async function checkout(){const P=C.P;if(Object.keys(P.sa||{}).length&&!P.bid)return toast("اختار الحلاق الأول قبل ما تحدد مساعد");
const items=[...P.s.map(id=>({type:"service",id,qty:1,assistant:(P.sa||{})[id]||null})),...P.p.map(x=>({type:"product",id:x.id,qty:x.q}))];
const{data,error}=await sb.rpc("checkout_invoice",{p_customer:P.cid?+P.cid:null,p_barber:P.bid||null,p_items:items,p_discount_pct:P.disc,p_method:P.pay,p_appointment:P.appt,p_redemption:P.rid?+P.rid:null});
if(error)return toast(error.message);C.P=null;toast("تم إصدار فاتورة رقم "+data);go("inv")}
async function setS(id,s){await sb.from("appointments").update({status:s}).eq("id",id);go("appts")}
function payAppt(id){const a=C.A.find(x=>x.id==id);C.P={s:a.appointment_services.map(x=>x.service_id),p:[],cid:a.customer_id,bid:a.barber_id||"",appt:id};go("pos")}
async function restock(id,q){const{error}=await sb.rpc("restock_product",{p_id:id,p_qty:10});error?toast(error.message):go("stock")}
// ===== شاشة الموظف والإدارة =====
const mm=x=>x==null?"—":fm(x);const KIND={advance:"سحب",deduction:"خصم",bonus:"مكافأة"};C.rg="month";
const rangeOf=k=>{const a=new Date();a.setHours(0,0,0,0);const b=new Date(a);
if(k=="week"){a.setDate(a.getDate()-((a.getDay()+1)%7));b.setTime(a.getTime());b.setDate(b.getDate()+7)}
else if(k=="month"){a.setDate(1);b.setTime(a.getTime());b.setMonth(b.getMonth()+1)}else b.setDate(b.getDate()+1);
return[a.toISOString(),b.toISOString()]};
async function panel(id,owner){
C.reload=()=>panel(id,owner);const[f,t]=rangeOf(C.rg);
const[{data:sm,error:e1},{data:al},{data:tx},{data:rv},{data:sc},{data:at},{data:op},{data:sh},{data:lv}]=await Promise.all([
sb.rpc("staff_summary",{p_staff:id,p_from:f,p_to:t}),
sb.rpc("assist_log",{p_staff:id,p_from:f,p_to:t}),
sb.from("staff_transactions").select("*").eq("staff_id",id).gte("created_at",f).lt("created_at",t).order("created_at",{ascending:false}),
sb.from("reviews").select("rating,tags,note,created_at").eq("barber_id",id).order("created_at",{ascending:false}).limit(20),
sb.rpc("staff_schedule",{p_staff:id}),sb.from("attendance").select("*").eq("staff_id",id).gte("check_in",f).lt("check_in",t).order("check_in",{ascending:false}),sb.from("attendance").select("id,check_in").eq("staff_id",id).is("check_out",null).limit(1),sb.from("staff_shifts").select("*").eq("staff_id",id),sb.from("staff_leaves").select("*").eq("staff_id",id).gte("to_date",new Date().toISOString().slice(0,10)).order("from_date")]);
if(e1)return $("panel").innerHTML=`<p class="m">${esc(e1.message)}</p>`;
const s=sm?.[0]||{},avg=rv?.length?(rv.reduce((a,r)=>a+r.rating,0)/rv.length).toFixed(1):"-";
const S=owner?{f:1,s:1,r:1}:{f:can("view_own_finance"),s:can("view_own_schedule"),r:can("view_own_reviews")};const card=(l,v,c)=>`<div class="box" style="text-align:center"><div class="m">${l}</div><div style="font-weight:800;font-size:19px;color:${c||"inherit"}">${v}</div></div>`;
const hm=d=>new Date(d).toLocaleTimeString("ar-EG",{hour:"2-digit",minute:"2-digit"}),DN=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
const attOn=owner||can("use_attendance");
const attBox=!owner&&can("use_attendance")?`<div class="box" style="margin:10px 0;text-align:center">${op?.length?`<div class="m">حاضر من ${hm(op[0].check_in)}</div><button class="btn" style="width:100%" onclick="att('check_out')">تسجيل انصراف</button>`:`<button class="btn" style="width:100%;background:var(--ok)" onclick="att('check_in')">تسجيل حضور</button>`}</div>`:"";
const hrs=(at||[]).reduce((a,r)=>a+((r.check_out?new Date(r.check_out):new Date())-new Date(r.check_in))/36e5,0),late=(at||[]).reduce((a,r)=>a+r.late_min,0);
const attHist=attOn?`<h2>الحضور والانصراف</h2><div class="m" style="margin-bottom:6px">${(at||[]).length} يوم · ${hrs.toFixed(1)} ساعة · تأخير ${late} دقيقة</div>${(at||[]).map(r=>`<div class="row"><div><b>${new Date(r.check_in).toLocaleDateString("ar-EG",{weekday:"short",day:"numeric",month:"numeric"})}</b><div class="m">${hm(r.check_in)} ← ${r.check_out?hm(r.check_out):"لسه حاضر"}</div></div><div style="text-align:left">${r.late_min?`<span class="tag" style="background:var(--red);color:#fff">متأخر ${r.late_min} د</span>`:`<span class="tag">في الميعاد</span>`}${r.note?`<div class="m">${esc(r.note)}</div>`:""}</div></div>`).join("")}`:"";
const shBox=`<h2>جدول شغلي</h2>${sh?.length?[0,1,2,3,4,5,6].map(d=>{const x=sh.find(y=>y.weekday==d);return x?`<div class="row"><b>${DN[d]}</b><span>${x.is_off?"إجازة":x.start_time.slice(0,5)+" ← "+x.end_time.slice(0,5)}</span></div>`:""}).join(""):`<p class="m">لسه مفيش شيفت محدد.</p>`}${lv?.length?`<div class="m">إجازات جاية:</div>`+lv.map(l=>`<div class="row"><span>${l.from_date} ← ${l.to_date}</span><span class="m">${esc(l.reason||"")}</span></div>`).join(""):""}`;
$("panel").innerHTML=`${attBox}<div class="chips">${[["day","اليوم"],["week","الأسبوع"],["month","الشهر"]].map(x=>`<button class="chip ${C.rg==x[0]?"sel":""}" onclick="C.rg='${x[0]}';C.reload()">${x[1]}</button>`).join("")}</div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">${s.who=="assistant"?card("راتب الفترة",mm(s.salary),"var(--ok)")+card("خدمات شاركت فيها",s.assisted??0):card("مبيعاتي"+(s.cuts==null?"":" ("+s.cuts+" زبون)"),mm(s.sales))+card("عمولتي",mm(s.commission),"var(--ok)")+(s.assistant_cuts==null?"":card("خصم مساعد",mm(s.assistant_cuts),"var(--red)"))}${card("مكافآت",mm(s.bonuses),"var(--ok)")}${card("سحب",mm(s.advances),"var(--red)")}${card("خصومات",mm(s.deductions),"var(--red)")}${card("الصافي المستحق",mm(s.net),"var(--brass)")}</div>
${owner?`<h2>تسجيل حركة</h2><div class="box"><select id="tk">${Object.entries(KIND).map(k=>`<option value="${k[0]}">${k[1]}</option>`).join("")}</select><input id="ta" type="number" inputmode="decimal" placeholder="المبلغ"><input id="tn" placeholder="ملاحظة (اختياري)"><button class="btn" onclick="addTx('${id}')">حفظ الحركة</button></div>`:""}
${al?.length?`<h2>${s.who=="assistant"?"الخدمات اللي شاركت فيها":"خصم المساعدين على خدماتك"}</h2>`+al.map(x=>`<div class="row"><div><b>#${x.inv_no}</b> · ${esc(x.service_name)} · ${fm(x.price)}<div class="m">${new Date(x.created).toLocaleDateString("ar-EG")} · ${s.who=="assistant"?"مع الحلاق "+esc(x.barber_name||"—"):"اتخصم للمساعد "+esc(x.assistant_name)}</div></div>${s.who=="assistant"?"":`<b style="color:var(--red)">- ${fm(x.cut)}</b>`}</div>`).join(""):""}
<h2 ${S.f?"":"hidden"}>الحركات</h2>${tx?.length?tx.map(x=>`<div class="row"><div><b style="color:${x.kind=="bonus"?"var(--ok)":"var(--red)"}">${KIND[x.kind]}</b> · ${fm(x.amount)}<div class="m">${new Date(x.created_at).toLocaleDateString("ar-EG")} ${esc(x.note||"")}</div></div>${owner?`<button class="btn s g" onclick="delTx(${x.id})">حذف</button>`:""}</div>`).join(""):`<p class="m" ${S.f?"":"hidden"}>مفيش حركات في الفترة دي.</p>`}
<h2 ${S.s?"":"hidden"}>دور زباينك (اليوم والجاي)</h2>${sc?.length?sc.map(a=>`<div class="row"><div><b>#${a.ticket_no}</b> · ${esc(a.customer_name)}${a.customer_phone?" · "+esc(a.customer_phone):""}<div class="m">${a.day} · ${PLB[a.period]} · ${esc(a.services)} · ${fm(a.total)}</div></div><div style="text-align:left"><span class="tag">${a.finished?"خلصت":a.called&&a.status=="upcoming"?"مستدعى"+(a.eta=="on_way"?" (في الطريق)":""):ST[a.status]}</span>${!owner?`<br>${a.status!="in_service"&&!a.called?`<button class="btn s" onclick="tk('call_ticket',${a.id})">استدعاء</button> `:""}${a.status!="in_service"?`<button class="btn s g" onclick="myS(${a.id},'in_service')">ابدأ</button>`:!a.finished?`<button class="btn s" onclick="tk('finish_ticket',${a.id})">خلصت</button>`:""}`:""}</div></div>`).join(""):`<p class="m" ${S.s?"":"hidden"}>مفيش زباين محجوزة.</p>`}
${attHist}${attOn?shBox:""}<h2 ${S.r?"":"hidden"}>تقييماتي (المتوسط ★ ${avg})</h2>${rv?.length?rv.map(r=>`<div class="row" style="display:block"><b style="color:var(--brass)">${"★".repeat(r.rating)}</b> <span class="m">${(r.tags||[]).map(esc).join(" · ")}</span>${r.note?`<div>${esc(r.note)}</div>`:""}</div>`).join(""):`<p class="m" ${S.r?"":"hidden"}>لسه مفيش تقييمات.</p>`}`}
async function addTx(id){const a=+$("ta").value;if(!(a>0))return toast("اكتب مبلغ صحيح");
const{error}=await sb.from("staff_transactions").insert({staff_id:id,kind:$("tk").value,amount:a,note:$("tn").value});error?toast(error.message):(toast("تم الحفظ"),C.reload())}
async function delTx(id){if(!confirm("حذف الحركة؟"))return;await sb.from("staff_transactions").delete().eq("id",id);C.reload()}
async function myS(id,st){const{error}=await sb.rpc("set_my_appt_status",{p_id:id,p_status:st});error?toast(error.message):C.reload()}
V.me=()=>{put(`<h1>شاشتي — ${esc(me.full_name)}</h1><div id="panel"></div>`);panel(me.id,false)};
V.team=async()=>{
const{data}=await sb.from("profiles").select("*").order("role").order("full_name");
const RL={owner:"مالك",cashier:"كاشير",barber:"حلاق",assistant:"مساعد",customer:"عميل"};
put(`<h1>الموظفين</h1><h2>إضافة موظف جديد</h2><div class="box"><input id="ns_n" placeholder="اسم الموظف"><input id="ns_e" type="text" placeholder="كود الموظف (مثلاً 101) - هيدخل بيه"><input id="ns_p" type="text" placeholder="كلمة سر (6 حروف على الأقل)"><div class="chips" style="align-items:center"><select id="ns_r" style="width:auto;margin:0"><option value="barber">حلاق</option><option value="assistant">مساعد</option><option value="cashier">كاشير</option></select><input id="ns_c" type="number" value="${C.cfg.default_commission||40}" style="width:80px;margin:0" aria-label="العمولة"><span class="m">% عمولة (للمساعد: نسبة خصم المحل من خدماته)</span></div><input id="ns_s" type="number" inputmode="decimal" placeholder="الراتب الشهري (للمساعد فقط)"><button class="btn" onclick="addStaff()">إضافة الموظف</button></div><h2>كل الحسابات</h2>`+data.map(p=>`<div class="row" style="display:block"><b>${esc(p.full_name)}</b> <span class="tag">${RL[p.role]}</span>${p.code?` <span class="m">كود ${esc(p.code)}</span>`:""}
<div class="chips" style="margin-top:8px;align-items:center"><select id="r${p.id}" style="width:auto;margin:0">${Object.entries(RL).map(r=>`<option value="${r[0]}" ${p.role==r[0]?"selected":""}>${r[1]}</option>`).join("")}</select><input id="c${p.id}" type="number" value="${p.commission_pct}" style="width:80px;margin:0" aria-label="العمولة %"><span class="m">%</span>${p.role=="assistant"?`<input id="s${p.id}" type="number" value="${+p.salary||0}" style="width:100px;margin:0" aria-label="الراتب الشهري"><span class="m">راتب شهري</span>`:""}<button class="btn s" onclick="saveP('${p.id}')">حفظ</button>${["barber","cashier","assistant"].includes(p.role)?`<button class="btn s g" onclick="openPerms('${p.id}')">الصلاحيات</button><button class="btn s g" onclick="openShift('${p.id}')">الشيفت والإجازة</button>`:""}${["barber","assistant"].includes(p.role)?`<button class="btn s g" onclick="openStaff('${p.id}','${esc(p.full_name)}')">الحساب</button>`:""}</div></div>`).join(""))};
async function saveP(id){const u={role:$("r"+id).value,commission_pct:+$("c"+id).value||0};if($("s"+id))u.salary=+$("s"+id).value||0;const{error}=await sb.from("profiles").update(u).eq("id",id);error?toast(error.message):(toast("تم الحفظ"),V.team())}
function openStaff(id,name){put(`<button class="btn g s" style="margin-top:12px" onclick="V.team()">‹ رجوع</button><h1>حساب ${name}</h1><div id="panel"></div>`);panel(id,true)}

// ===== الصلاحيات =====
const PERMS=[["ط","الكاشير والمخزون"],["use_pos","يستخدم الكاشير ويصدر فواتير"],["view_stock","يشوف المخزون"],["restock","يوَرّد مخزون"],["view_invoices","يشوف كل الفواتير"],["ط","الحجوزات والعملاء"],["manage_appts","يشوف كل الحجوزات ويعدّل حالتها"],["view_customers","يشوف قائمة العملاء"],["view_customer_phone","يشوف أرقام تليفونات العملاء"],["view_reports","يشوف التقارير والأرباح"],["ط","شاشته الشخصية"],["use_attendance","يسجل حضور وانصراف من موبايله"],["view_own_schedule","يشوف جدول زباينه"],["view_own_sales","يشوف مبيعاته"],["view_own_commission","يشوف عمولته"],["view_own_finance","يشوف السحب والخصومات والمكافآت والصافي"],["view_own_reviews","يشوف تقييماته"]];
async function openPerms(id){const{data:p}=await sb.from("profiles").select("*").eq("id",id).single();C.pp=p;
put(`<button class="btn g s" style="margin-top:12px" onclick="V.team()">‹ رجوع</button><h1>صلاحيات ${esc(p.full_name)}</h1><p class="m">اللي مش متعلّم عليه، الموظف مش هيشوفه ولا هيقدر يوصله حتى من برّه التطبيق.</p>`+PERMS.map(x=>x[0]=="ط"?`<h2>${x[1]}</h2>`:`<label class="row" style="cursor:pointer"><span>${x[1]}</span><input type="checkbox" id="p_${x[0]}" ${can(x[0],p)?"checked":""} style="width:22px;height:22px;margin:0"></label>`).join("")+`<div class="chips" style="margin-top:12px"><button class="btn" onclick="savePerms()">حفظ الصلاحيات</button><button class="btn g" onclick="resetPerms()">رجوع للافتراضي</button></div>`)}
async function savePerms(){const o={};PERMS.forEach(x=>{if(x[0]!="ط")o[x[0]]=$("p_"+x[0]).checked});const{error}=await sb.from("profiles").update({perms:o}).eq("id",C.pp.id);error?toast(error.message):toast("تم حفظ الصلاحيات")}
async function resetPerms(){await sb.from("profiles").update({perms:{}}).eq("id",C.pp.id);toast("رجع للافتراضي");openPerms(C.pp.id)}
// ===== الإعدادات =====
V.none=()=>put(`<h1>حسابك متسجل ✓</h1><p class="m">المالك لسه ما فعّلش صلاحيات لحسابك. كلّمه يفتحها لك.</p>`);
V.set=async()=>{await loadCfg();const c=C.cfg;
const[{data:sv},{data:pr},{data:rw}]=await Promise.all([sb.from("services").select("*").order("id"),sb.from("products").select("*").order("id"),sb.from("loyalty_rewards").select("*").order("cost")]);C.cat={services:sv,products:pr};
const f=(k,l,t="text")=>`<label class="m">${l}</label><input id="s_${k}" type="${t}" value="${esc(c[k])}">`;
put(`<h1>الإعدادات</h1><h2>بيانات الصالون</h2><div class="box">${f("salon_name","اسم الصالون")}${f("phone","التليفون")}${f("address","العنوان")}${f("currency","العملة")}</div>
<h2>الحجز أونلاين</h2><div class="box"><label class="row" style="cursor:pointer"><span>الحجز أونلاين شغّال</span><input type="checkbox" id="s_booking_open" ${c.booking_open?"checked":""} style="width:22px;height:22px;margin:0"></label>${f("open_hour","ساعة الفتح (0-23)","number")}${f("close_hour","ساعة القفل (0-23)","number")}${f("slot_minutes","مدة الميعاد بالدقايق","number")}${f("days_ahead","الحجز قبلها بكام يوم","number")}<label class="m">يوم الإجازة الأسبوعي</label><select id="s_weekly_off">${["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"].map((d,i)=>`<option value="${i}" ${c.weekly_off==i?"selected":""}>${d}</option>`).join("")}<option value="-1" ${c.weekly_off==-1?"selected":""}>مفيش إجازة</option></select>${f("cancel_before_hours","أقل مدة للإلغاء قبل الميعاد (ساعات)","number")}</div>
<h2>الكاشير والولاء</h2><div class="box">${f("max_discount_pct","أقصى خصم للكاشير %","number")}${f("points_per_currency","كل كام جنيه = نقطة ولاء","number")}</div>
<h2>الحضور بالموقع</h2><div class="box">${f("salon_lat","خط عرض الصالون (lat)","number")}${f("salon_lng","خط طول الصالون (lng)","number")}<button class="btn g s" style="margin-bottom:8px" onclick="setHere()">📍 استخدم موقعي الحالي (وانت في الصالون)</button>${f("attendance_radius_m","النطاق المسموح بالمتر","number")}</div>
<h2>الدور</h2><div class="box">${f("max_queue_per_period","أقصى عدد زباين في الفترة لكل حلاق","number")}</div>
<h2>نقاط الولاء</h2><div class="box">${f("welcome_bonus","هدية التسجيل (نقاط)","number")}${f("review_bonus","نقاط التقييم","number")}${f("visit_bonus_every","مكافأة كل كام زيارة","number")}${f("visit_bonus_points","نقاط مكافأة الزيارات","number")}${f("tier_silver","نقاط المستوى الفضي (إجمالي)","number")}${f("tier_gold","نقاط المستوى الذهبي","number")}${f("tier_vip","نقاط مستوى VIP","number")}</div>
<button class="btn" style="width:100%;margin-top:10px" onclick="saveCfg()">حفظ الإعدادات</button>
<h2>الخدمات</h2>${sv.map(x=>`<div class="row"><div><b>${esc(x.name)}</b> · ${x.price}<div class="m">${x.duration_min} دقيقة ${x.active?"":"· موقوفة"}</div></div><div><button class="btn s g" onclick="editItem('services',${x.id})">تعديل</button> <button class="btn s g" onclick="toggleItem('services',${x.id},${!x.active})">${x.active?"إيقاف":"تفعيل"}</button></div></div>`).join("")}<button class="btn g s" onclick="addItem('services')">+ خدمة جديدة</button>
<h2>المنتجات</h2>${pr.map(x=>`<div class="row"><div><b>${esc(x.name)}</b> · بيع ${x.price} · شراء ${x.cost}<div class="m">الحد الأدنى ${x.min_stock} ${x.active?"":"· موقوف"}</div></div><div><button class="btn s g" onclick="editItem('products',${x.id})">تعديل</button> <button class="btn s g" onclick="toggleItem('products',${x.id},${!x.active})">${x.active?"إيقاف":"تفعيل"}</button></div></div>`).join("")}<button class="btn g s" onclick="addItem('products')">+ منتج جديد</button><h2>مكافآت الولاء</h2>${(rw||[]).map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="m">${x.cost} نقطة ${x.active?"":"· موقوفة"}</div></div><button class="btn s g" onclick="togRw(${x.id},${!x.active})">${x.active?"إيقاف":"تفعيل"}</button></div>`).join("")}<button class="btn g s" onclick="addRw()">+ مكافأة جديدة</button>`)};
async function saveCfg(){const T=["salon_name","phone","address","currency"],N=["open_hour","close_hour","slot_minutes","days_ahead","weekly_off","cancel_before_hours","max_discount_pct","points_per_currency","attendance_radius_m","max_queue_per_period","welcome_bonus","review_bonus","visit_bonus_every","visit_bonus_points","tier_silver","tier_gold","tier_vip"];
const rows=[...T.map(k=>({key:k,value:$("s_"+k).value})),...N.map(k=>({key:k,value:+$("s_"+k).value})),{key:"booking_open",value:$("s_booking_open").checked},...["salon_lat","salon_lng"].filter(k=>$("s_"+k).value!=="").map(k=>({key:k,value:+$("s_"+k).value}))];
if(rows.find(r=>r.key=="open_hour").value>=rows.find(r=>r.key=="close_hour").value)return toast("ساعة الفتح لازم تكون قبل القفل");
const{error}=await sb.from("app_settings").upsert(rows);error?toast(error.message):(toast("تم حفظ الإعدادات"),loadCfg())}
async function editItem(t,id){const x=C.cat[t].find(y=>y.id==id),n=prompt("الاسم",x.name);if(n===null)return;const pr=prompt("سعر البيع",x.price);if(pr===null)return;const u={name:n,price:+pr};
if(t=="services"){const d=prompt("المدة بالدقايق",x.duration_min);if(d===null)return;u.duration_min=+d;u.category=prompt("القسم (قصات / ذقن / عناية ...)",x.category||"قصات")||"قصات";u.description=prompt("وصف قصير (اختياري)",x.description||"")||null}else{const c=prompt("سعر الشراء",x.cost);if(c===null)return;const m=prompt("الحد الأدنى للمخزون",x.min_stock);if(m===null)return;u.cost=+c;u.min_stock=+m}
const{error}=await sb.from(t).update(u).eq("id",id);error?toast(error.message):V.set()}
async function toggleItem(t,id,a){await sb.from(t).update({active:a}).eq("id",id);V.set()}
async function addItem(t){const n=prompt("الاسم");if(!n)return;const pr=+prompt("سعر البيع");if(!(pr>=0))return;const o=t=="services"?{name:n,price:pr,duration_min:+prompt("المدة بالدقايق","30")||30,category:prompt("القسم (قصات / ذقن / عناية ...)","قصات")||"قصات"}:{name:n,price:pr,cost:+prompt("سعر الشراء","0")||0,stock:+prompt("الكمية الحالية","0")||0,min_stock:+C.cfg.low_stock_default||5};
const{error}=await sb.from(t).insert(o);error?toast(error.message):V.set()}

async function addStaff(){
const n=$("ns_n").value.trim(),e=(x=>x.includes("@")?x:x+"@staff.abu-yousef-salon.com")($("ns_e").value.trim()),pw=$("ns_p").value,r=$("ns_r").value,c=+$("ns_c").value||0,sal=+($("ns_s")?.value)||0;
if(!n||!e||pw.length<6)return toast("اكمل الاسم والبريد وكلمة سر 6 حروف");
const tmp=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false,storageKey:"tmp-signup"}});
const{data,error}=await tmp.auth.signUp({email:e,password:pw,options:{data:{full_name:n}}});
if(error)return toast(error.message);
if(!data.user||!(data.user.identities||[]).length)return toast("البريد ده مسجل قبل كده، غيّر دوره من القائمة تحت");
const{error:e2}=await sb.from("profiles").update({role:r,commission_pct:c,full_name:n,code:e.split("@")[0],...(r=="assistant"?{salary:sal}:{})}).eq("id",data.user.id);
if(e2)return toast(e2.message);
toast("تمت إضافة "+n+" ✓ — كوده "+e.split("@")[0]);V.team()}

async function att(f){const{data,error}=await sb.rpc(f);error?toast(error.message):(toast(data),C.reload())}
// ===== شيفت وإجازة (المالك) =====
async function openShift(id){
const[{data:p},{data:sh},{data:lv}]=await Promise.all([sb.from("profiles").select("full_name").eq("id",id).single(),sb.from("staff_shifts").select("*").eq("staff_id",id),sb.from("staff_leaves").select("*").eq("staff_id",id).order("from_date",{ascending:false}).limit(15)]);
C.sid=id;const DN=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
put(`<button class="btn g s" style="margin-top:12px" onclick="V.team()">‹ رجوع</button><h1>شيفت ${esc(p.full_name)}</h1><h2>الأسبوع</h2>`+DN.map((d,i)=>{const x=(sh||[]).find(y=>y.weekday==i)||{is_off:false,start_time:"10:00",end_time:"20:00"};return `<div class="row"><b style="min-width:62px">${d}</b><label class="m"><input type="checkbox" id="o${i}" ${x.is_off?"checked":""}> إجازة</label><input type="time" id="a${i}" value="${x.start_time.slice(0,5)}" style="width:auto;margin:0"><input type="time" id="b${i}" value="${x.end_time.slice(0,5)}" style="width:auto;margin:0"></div>`}).join("")+`<button class="btn" style="width:100%" onclick="saveShift()">حفظ الشيفت</button>
<h2>إجازة محددة</h2><div class="box"><label class="m">من</label><input type="date" id="lf"><label class="m">إلى</label><input type="date" id="lt"><input id="lr" placeholder="السبب (اختياري)"><button class="btn" onclick="addLeave()">إضافة الإجازة</button></div>`+(lv||[]).map(l=>`<div class="row"><div>${l.from_date} ← ${l.to_date}<div class="m">${esc(l.reason||"")}</div></div><button class="btn s g" onclick="delLeave(${l.id})">حذف</button></div>`).join(""))}
async function saveShift(){const rows=[0,1,2,3,4,5,6].map(i=>({staff_id:C.sid,weekday:i,is_off:$("o"+i).checked,start_time:$("a"+i).value||"10:00",end_time:$("b"+i).value||"20:00"}));
if(rows.some(r=>!r.is_off&&r.start_time>=r.end_time))return toast("وقت البداية لازم يسبق النهاية");
const{error}=await sb.from("staff_shifts").upsert(rows);error?toast(error.message):toast("تم حفظ الشيفت")}
async function addLeave(){const f=$("lf").value,t=$("lt").value||f;if(!f)return toast("اختار تاريخ البداية");if(t<f)return toast("تاريخ النهاية قبل البداية");
const{error}=await sb.from("staff_leaves").insert({staff_id:C.sid,from_date:f,to_date:t,reason:$("lr").value});error?toast(error.message):(toast("تمت إضافة الإجازة"),openShift(C.sid))}
async function delLeave(id){await sb.from("staff_leaves").delete().eq("id",id);openShift(C.sid)}

// ================= نظام الدور + العميل (مرة واحدة) =================
const PERIODS=[["morning","الصبح","6ص–12ظ",12],["afternoon","العصر","12–5م",17],["evening","المساء","5م–12",24],["night","بعد منتصف الليل","12–6ص",6]];
const PLB={morning:"الصبح",afternoon:"العصر",evening:"المساء",night:"بعد منتصف الليل"};
const MAIL="@staff.abu-yousef-salon.com";
function authView(m="c"){put(`<h1>أهلاً بيك في ${esc(C.cfg.salon_name)}</h1>`+(m=="c"?`<p class="m">سجّل مرة واحدة بس، وبعد كده هتدخل على حسابك علطول من نفس الموبايل.</p><div class="box"><input id="cn" placeholder="اسمك"><input id="cp" type="tel" inputmode="numeric" placeholder="رقم موبايلك (01xxxxxxxxx)"><button class="btn" style="width:100%" onclick="regCustomer()">ابدأ</button></div><p class="m" style="text-align:center;margin-top:18px"><a href="#" style="color:var(--blue)" onclick="authView('s');return false">دخول الموظفين</a></p>`:`<div class="box"><input id="em" placeholder="كود الموظف (أو البريد للمالك)"><input id="pw" type="password" placeholder="كلمة السر"><button class="btn" style="width:100%" onclick="login()">دخول</button></div><p class="m"><a href="#" style="color:var(--blue)" onclick="authView('c');return false">← رجوع للعملاء</a></p>`))}
async function login(){const x=$("em").value.trim(),email=x.includes("@")?x:x+MAIL;const{error}=await sb.auth.signInWithPassword({email,password:$("pw").value});error?toast("الكود أو كلمة السر غلط"):boot()}
async function regCustomer(){const n=$("cn").value.trim(),ph=$("cp").value.replace(/\D/g,"");
if(n.length<2)return toast("اكتب اسمك");if(!/^01\d{9}$/.test(ph))return toast("الموبايل لازم 11 رقم ويبدأ بـ 01");
const{data:{session:ss}}=await sb.auth.getSession();
if(ss){const{error}=await sb.rpc("register_customer",{p_name:n,p_phone:ph});return error?toast(error.message):boot()}
const pw=crypto.randomUUID().replace(/-/g,""),email=ph+"@c.abu-yousef-salon.com";
const{data,error}=await sb.auth.signUp({email,password:pw,options:{data:{full_name:n}}});
if(error)return toast(error.message);
if(!data.user||!(data.user.identities||[]).length)return toast("الرقم ده مسجل قبل كده من جهاز تاني. كلّم الصالون.");
try{localStorage.setItem("salon_cred",JSON.stringify({e:email,p:pw}))}catch(e){}
if(!data.session){const r=await sb.auth.signInWithPassword({email,password:pw});if(r.error)return toast(r.error.message)}
const{error:e2}=await sb.rpc("register_customer",{p_name:n,p_phone:ph});e2?toast(e2.message):boot()}
const bkDays=()=>[...Array(+C.cfg.days_ahead)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return{i,iso:d.toLocaleDateString("en-CA"),off:d.getDay()==C.cfg.weekly_off,l:i?d.toLocaleDateString("ar-EG",{weekday:"short",day:"numeric",month:"numeric"}):"اليوم"}});
V.book=async()=>{if(!C.cfg.booking_open)return put(`<h1>احجز دورك</h1><p class="m">الحجز متوقف حاليًا.</p>`);
const{data}=await sb.from("services").select("*").eq("active",true).order("id");C.sv=data||[];C.b=C.b||{s:[],barber:undefined,day:0,period:null};drawBk()};
function drawBk(){const b=C.b,days=bkDays();
put(`<div class="hello">أهلاً ${esc((me.full_name||"").split(" ")[0])}</div><h1>احجز دورك</h1><h2>الخدمات</h2><div class="chips">${C.sv.map(x=>`<button class="chip ${b.s.includes(x.id)?"sel":""}" onclick="tgS(${x.id})">${esc(x.name)} · ${x.price}</button>`).join("")}</div>
<h2>اليوم</h2><div class="chips">${days.map(x=>`<button class="chip ${b.day==x.i?"sel":""}" ${x.off?"disabled":""} onclick="C.b.day=${x.i};C.b.period=null;C.b.barber=undefined;drawBk()">${x.l}</button>`).join("")}</div>
<h2>الفترة</h2><div class="chips">${PERIODS.map(p=>`<button class="chip ${b.period==p[0]?"sel":""}" ${b.day==0&&new Date().getHours()>=p[3]?"disabled":""} onclick="C.b.period='${p[0]}';C.b.barber=undefined;drawBk()">${p[1]} <span class="m">${p[2]}</span></button>`).join("")}</div><div id="bl"></div>`);if(b.period)loadBarbers()}
function tgS(id){const b=C.b;b.s=b.s.includes(id)?b.s.filter(x=>x!=id):[...b.s,id];drawBk()}
async function loadBarbers(){const b=C.b,d=bkDays()[b.day];const{data,error}=await sb.rpc("available_barbers",{p_day:d.iso,p_period:b.period});if(error)return toast(error.message);
const L=data||[],sel=v=>b.barber===v?"border-color:var(--blue);box-shadow:0 0 0 2px var(--blue) inset;":"";
const sv=C.sv.filter(x=>b.s.includes(x.id)),tot=sv.reduce((a,x)=>a+x.price,0),dur=sv.reduce((a,x)=>a+x.duration_min,0);
$("bl").innerHTML=`<h2>الحلاق</h2>`+(L.length?`<button class="row" style="cursor:pointer;${sel(null)}" onclick="C.b.barber=null;loadBarbers()"><b>أي حلاق (الأقل زحمة)</b><span class="m">أسرع دور</span></button>`+L.map(x=>`<button class="row" style="cursor:pointer;${sel(x.id)}" onclick="C.b.barber='${x.id}';loadBarbers()"><b>${esc(x.full_name)}</b><span class="m">${x.waiting} في الدور · ~${x.est_min} دقيقة</span></button>`).join("")+`<button class="btn" style="width:100%;margin-top:8px" ${b.s.length&&b.barber!==undefined?"":"disabled"} onclick="bookNow()">تأكيد وخد رقم دورك · ${fm(tot)} · ~${dur} دقيقة</button>`:`<p class="m">مفيش حلاق متاح في الفترة دي، جرّب فترة تانية.</p>`)}
async function bookNow(){const b=C.b,d=bkDays()[b.day];const{error}=await sb.rpc("book_ticket",{p_barber:b.barber||null,p_day:d.iso,p_period:b.period,p_services:b.s});
if(error)return toast(error.code=="23505"?"حد حجز قبلك، جرّب تاني":error.message);C.b=null;toast("تم الحجز ✓ ده رقم دورك");go("queue")}
V.queue=async()=>{const{data:h}=await sb.rpc("my_history");const L=h||[],act=L.find(x=>["upcoming","checked_in","in_service"].includes(x.status)),fin=L.find(x=>x.status=="done"&&!x.rated);
if(act){const{data:q}=await sb.rpc("queue_status",{p_id:act.id});if(!q?.[0])return;drawQ(q[0]);clearInterval(C.poll);C.poll=setInterval(()=>tab=="queue"&&($("app").classList.add("still"),V.queue()),8000);return}
if(fin)return rateView2(fin.id);
put(`<h1>دوري</h1><div class="box" style="text-align:center"><p class="m">مفيش دور نشط دلوقتي.</p><button class="btn" onclick="go('book')">احجز دورك</button></div>`)};
function drawQ(s){C.qid=s.id;const st=s.status,steps=[["مستني دورك",1],["اتنادى عليك",s.called||st!="upcoming"],["وصلت الصالون",st=="checked_in"||st=="in_service"],["بدأت الخدمة",st=="in_service"],["خلصت — ادفع عند الكاشير",s.finished]];
put(`<h1>دوري</h1><div class="box" style="text-align:center"><div class="m">رقمك</div><div style="font-size:64px;font-weight:800;color:var(--red);line-height:1.1">${s.ticket_no}</div><div class="m">${PLB[s.period]} · ${s.day}</div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px"><div><div class="m">بيحلق دلوقتي مع ${esc(s.barber_name)}</div><b style="font-size:22px">${s.current_no?"رقم "+s.current_no:"لسه محدش"}</b></div><div><div class="m">قدامك</div><b style="font-size:22px">${s.ahead} زبون</b></div></div><div class="m" style="margin-top:8px">الوقت المتوقع: حوالي ${s.est_min} دقيقة</div></div>
<div class="row" style="margin-top:10px"><span>${esc(s.services)}</span><b>${fm(s.total)}</b></div>
${s.called&&st=="upcoming"?`<div class="box" style="margin:10px 0;border-color:var(--red)"><b>🔔 اتنادى عليك!</b><div class="chips" style="margin-top:8px"><button class="btn" ${s.eta=="on_way"?"disabled":""} onclick="eta('on_way')">أنا في الطريق</button><button class="btn" style="background:var(--ok)" onclick="eta('arrived')">وصلت</button></div></div>`:""}
<div style="margin:12px 0">${steps.map(x=>`<div style="padding:3px 0;${x[1]?"":"opacity:.4"}">${x[1]?"✓":"○"} ${x[0]}</div>`).join("")}</div>
${!s.called&&st=="upcoming"?`<button class="btn g" style="width:100%" onclick="cancelT()">إلغاء الحجز</button>`:""}`)}
async function eta(st){const{error}=await sb.rpc("ticket_eta",{p_id:C.qid,p_state:st});error?toast(error.message):(toast(st=="arrived"?"تمام، الصالون عرف إنك وصلت":"تمام، مستنينك"),V.queue())}
async function cancelT(){if(!confirm("تلغي الحجز؟"))return;const{error}=await sb.rpc("cancel_my_appt",{p_id:C.qid});error?toast(error.message):go("book")}
function rateView2(id){C.R2={id,b:0,s:0,p:0,tg:[],note:""};drawR2()}
const stars=(k,v)=>`<div class="stars" style="text-align:center">${[1,2,3,4,5].map(i=>`<button class="${v>=i?"on":""}" aria-label="${i}" onclick="C.R2.${k}=${i};drawR2()">★</button>`).join("")}</div>`;
function drawR2(){const R=C.R2,tags=["نظافة المكان","دقة الدور","مهارة الحلاق","سعر مناسب","تعامل راقي"];
put(`<h1 style="text-align:center">خلصت؟ قيّم تجربتك</h1><p class="m" style="text-align:center">هتاخد ${C.cfg.review_bonus} نقطة هدية على تقييمك 🎁</p><h2>الحلاق</h2>${stars("b",R.b)}<h2>الخدمة</h2>${stars("s",R.s)}<h2>المكان</h2>${stars("p",R.p)}<div class="chips" style="margin-top:8px">${tags.map(t=>`<button class="chip ${R.tg.includes(t)?"sel":""}" onclick="C.R2.tg=C.R2.tg.includes('${t}')?C.R2.tg.filter(x=>x!='${t}'):[...C.R2.tg,'${t}'];drawR2()">${t}</button>`).join("")}</div><input placeholder="ملاحظات (اختياري)" value="${esc(R.note)}" oninput="C.R2.note=this.value"><button class="btn" style="width:100%" ${R.b&&R.s&&R.p?"":"disabled"} onclick="sendR2()">إرسال</button>`)}
async function sendR2(){const R=C.R2;const{error}=await sb.rpc("rate_ticket",{p_appt:R.id,p_barber:R.b,p_service:R.s,p_place:R.p,p_tags:R.tg,p_note:R.note});error?toast(error.message):(toast("شكرًا! اتضافت نقاط لحسابك 🎁"),go("loy"))}
V.mine=async()=>{const{data:h}=await sb.rpc("my_history");const L=h||[],dn=L.filter(x=>x.status=="done"),paid=dn.reduce((a,x)=>a+(+x.paid||0),0);
put(`<h1>حجوزاتي</h1><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px"><div class="box" style="text-align:center"><div class="m">زياراتك</div><b>${dn.length}</b></div><div class="box" style="text-align:center"><div class="m">آخر زيارة</div><b style="font-size:13px">${dn[0]?.day||"—"}</b></div><div class="box" style="text-align:center"><div class="m">إجمالي دفعك</div><b style="font-size:14px">${fm(paid)}</b></div></div><h2>السجل</h2>`+(L.length?L.map(x=>`<div class="row"><div><b>${x.day||""}</b> · ${PLB[x.period]||""} · دور ${x.ticket_no||"-"}<div class="m">${esc(x.services)} مع ${esc(x.barber_name||"-")}</div></div><div style="text-align:left"><span class="tag">${ST[x.status]}</span>${x.paid!=null?`<div><b>${fm(x.paid)}</b></div>`:""}${x.points?`<div class="m">+${x.points} نقطة</div>`:""}</div></div>`).join(""):`<p class="m">لسه معندكش حجوزات.</p>`))};
const RSN={purchase:"شراء",welcome:"هدية التسجيل",review:"تقييم",visit:"مكافأة زيارات",redeem:"استبدال مكافأة",adjust:"تعديل من الإدارة"};
V.loy=async()=>{const{data:{user}}=await sb.auth.getUser();const{data:c}=await sb.from("customers").select("id,points,lifetime_points,visits").eq("user_id",user.id).single();
const[{data:tr},{data:rw},{data:vo},{data:lg}]=await Promise.all([sb.rpc("loyalty_tier",{p_life:c.lifetime_points}),sb.from("loyalty_rewards").select("*").eq("active",true).order("cost"),sb.from("loyalty_redemptions").select("code,loyalty_rewards(name)").eq("customer_id",c.id).eq("status","active"),sb.from("loyalty_ledger").select("*").eq("customer_id",c.id).order("created_at",{ascending:false}).limit(15)]);
const t=tr[0],pct=t.next_at?Math.min(100,c.lifetime_points/t.next_at*100):100,g=C.cfg;
put(`<h1>نقاطي</h1><div class="box" style="text-align:center"><div class="m">رصيدك</div><div style="font-size:46px;font-weight:800;color:var(--brass);line-height:1.2">${c.points}</div><span class="tag" style="background:var(--brass);color:#fff">مستوى ${t.name}${t.mult>1?" · نقاط ×"+t.mult:""}</span><div class="bar" style="margin:12px 0 4px;height:8px;border-radius:6px;background:var(--line);overflow:hidden"><i style="display:block;height:100%;width:${pct}%;background:var(--blue)"></i></div><div class="m">${t.next_at?"باقي "+(t.next_at-c.lifetime_points)+" نقطة للمستوى الجاي":"وصلت لأعلى مستوى 👑"}</div></div>
<h2>إزاي تكسب نقاط؟</h2><div class="box m">• كل ${g.points_per_currency} ${g.currency} = نقطة (× مستواك)<br>• ${g.review_bonus} نقطة على كل تقييم<br>• ${g.visit_bonus_points} نقطة كل ${g.visit_bonus_every} زيارات<br>• ${g.welcome_bonus} نقطة هدية التسجيل</div>
${vo?.length?`<h2>كوبوناتك (قدّم الكود للكاشير)</h2>`+vo.map(v=>`<div class="row"><span>${esc(v.loyalty_rewards.name)}</span><b style="font-size:20px;letter-spacing:2px;color:var(--red)">${v.code}</b></div>`).join(""):""}
<h2>استبدل نقاطك</h2>`+(rw||[]).map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="m">${x.cost} نقطة</div></div><button class="btn s" ${c.points<x.cost?"disabled":""} onclick="redeem(${x.id})">استبدل</button></div>`).join("")+`<h2>آخر الحركات</h2>`+((lg||[]).length?lg.map(l=>`<div class="row"><div>${RSN[l.reason]||l.reason}<div class="m">${new Date(l.created_at).toLocaleDateString("ar-EG")}</div></div><b style="color:${l.points>0?"var(--ok)":"var(--red)"}">${l.points>0?"+":""}${l.points}</b></div>`).join(""):`<p class="m">لسه مفيش حركات.</p>`))};
async function redeem(id){if(!confirm("تستبدل النقاط دي؟"))return;const{data,error}=await sb.rpc("redeem_reward",{p_reward:id});error?toast(error.message):(toast("كود الكوبون: "+data),V.loy())}
V.menu=async()=>{const{data}=await sb.from("services").select("*").eq("active",true).order("category").order("price");const g={};(data||[]).forEach(x=>(g[x.category||"خدمات"]=g[x.category||"خدمات"]||[]).push(x));
put(`<h1>منيو الخدمات</h1>`+Object.entries(g).map(([k,a])=>`<h2>${esc(k)}</h2>`+a.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="m">${esc(x.description||"")} ${x.duration_min} دقيقة</div></div><div style="text-align:left"><b style="color:var(--brass)">${fm(x.price)}</b><br><button class="btn s g" onclick="C.b=C.b||{s:[],barber:undefined,day:0,period:null};C.b.s=[${x.id}];go('book')">احجز</button></div></div>`).join("")).join(""))};
// ================= موظفين: الدور والحضور بالموقع =================
V.appts=async()=>{const t=new Date().toLocaleDateString("en-CA");
const{data}=await sb.from("appointments").select("id,day,period,ticket_no,status,called_at,eta,finished_at,customer_id,barber_id,customers(name),profiles(full_name),appointment_services(service_id,services(name))").gte("day",t).not("status","in","(cancelled,done)").order("day").order("ticket_no");
C.A=data||[];put(`<h1>الدور</h1>`+(C.A.length?C.A.map(a=>`<div class="row"><div><b>#${a.ticket_no}</b> · ${esc(a.customers?.name)}<div class="m">${a.day} · ${PLB[a.period]} · ${a.appointment_services.map(x=>esc(x.services.name)).join(" + ")} · ${esc(a.profiles?.full_name||"-")}</div></div><div style="text-align:left"><span class="tag">${a.finished_at?"خلص":a.called_at&&a.status=="upcoming"?"مستدعى"+(a.eta=="on_way"?" (في الطريق)":""):ST[a.status]}</span><br>${a.status=="upcoming"&&!a.called_at?`<button class="btn s" onclick="tk('call_ticket',${a.id})">استدعاء</button> `:""}${a.status=="upcoming"||a.status=="checked_in"?`<button class="btn s g" onclick="setS(${a.id},'in_service')">ابدأ</button> `:""}${a.status=="in_service"?`<button class="btn s" onclick="payAppt(${a.id})">دفع</button> `:""}${a.status!="in_service"?`<button class="btn s g" onclick="setS(${a.id},'cancelled')">إلغاء</button>`:""}</div></div>`).join(""):`<p class="m">مفيش دور محجوز.</p>`))};
async function tk(f,id){const{error}=await sb.rpc(f,{p_id:id});error?toast(error.message):(tab=="appts"?go("appts"):C.reload())}
async function loadV(){const P=C.P;P.rid="";P.vs=[];if(P.cid){const{data}=await sb.from("loyalty_redemptions").select("id,code,loyalty_rewards(name)").eq("customer_id",P.cid).eq("status","active");P.vs=data||[]}drawPos()}
const getPos=()=>new Promise(r=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>r({lat:p.coords.latitude,lng:p.coords.longitude}),()=>r({}),{enableHighAccuracy:true,timeout:12000,maximumAge:0}):r({}));
async function att(f){toast("بنحدد موقعك...");const g=await getPos();const{data,error}=await sb.rpc(f,{p_lat:g.lat??null,p_lng:g.lng??null});error?toast(error.message):(toast(data),C.reload())}
async function setHere(){const g=await getPos();if(g.lat==null)return toast("فعّل الموقع واسمح للمتصفح");$("s_salon_lat").value=g.lat;$("s_salon_lng").value=g.lng;toast("اتحط موقعك الحالي، اضغط حفظ الإعدادات")}
async function addRw(){const n=prompt("اسم المكافأة");if(!n)return;const c=+prompt("تكلفتها بالنقاط","100");if(!(c>0))return;const k=prompt("النوع: 1 خصم بمبلغ، 2 خصم نسبة %، 3 خدمة مجانية","1");const o={name:n,cost:c};
if(k=="2"){o.kind="pct";o.value=+prompt("نسبة الخصم %","10")}else if(k=="3"){const sv=C.cat.services,i=+prompt("اكتب رقم الخدمة:\n"+sv.map((x,j)=>(j+1)+" "+x.name).join("\n"));if(!sv[i-1])return;o.kind="service";o.service_id=sv[i-1].id;o.value=0}else{o.kind="amount";o.value=+prompt("قيمة الخصم بالجنيه","20")}
const{error}=await sb.from("loyalty_rewards").insert(o);error?toast(error.message):V.set()}
async function togRw(id,a){await sb.from("loyalty_rewards").update({active:a}).eq("id",id);V.set()}

// ================= صفحتين منفصلتين: عميل / موظف =================
function authView(){put(`<h1>أهلاً بيك في ${esc(C.cfg.salon_name)}</h1>`+(APP_MODE=="staff"?`<p class="m">صفحة الموظفين والإدارة.</p><div class="box"><input id="em" placeholder="كود الموظف (أو البريد للمالك)" autocomplete="username"><input id="pw" type="password" placeholder="كلمة السر" autocomplete="current-password"><button class="btn" style="width:100%" onclick="login()">دخول</button></div>`:`<p class="m">سجّل مرة واحدة بس، وبعد كده هتدخل على حسابك علطول من نفس الموبايل.</p><div class="box"><input id="cn" placeholder="اسمك"><input id="cp" type="tel" inputmode="numeric" placeholder="رقم موبايلك (01xxxxxxxxx)"><button class="btn" style="width:100%" onclick="regCustomer()">ابدأ</button></div>`))}
function wrongPage(k){put(`<h1>${k=="staff"?"ده حساب موظف":"ده حساب عميل"}</h1><p class="m">${k=="staff"?"ادخل من صفحة الموظفين.":"صفحة الموظفين للموظفين بس."}</p><div class="chips"><a class="btn" style="text-decoration:none" href="${k=="staff"?"/staff":"/"}">${k=="staff"?"صفحة الموظفين":"صفحة العملاء"}</a>${k=="customer"?`<button class="btn g" onclick="sb.auth.signOut().then(()=>boot())">دخول بحساب موظف</button>`:""}</div>`)}
// ================= الإعدادات: تاب لكل قسم + تصفير =================
const SEC=[["general","عام"],["book","الحجوزات"],["staff","الموظفين"],["pos","الكاشير"],["stock","المخزون"],["loy","العملاء والولاء"],["danger","تصفير"]];
const DAYS7=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
const FLD={general:[["salon_name","اسم الصالون"],["phone","التليفون"],["address","العنوان"],["currency","العملة"],["timezone","المنطقة الزمنية (مثال: Africa/Cairo)"]],
book:[["booking_open","الحجز أونلاين شغّال","bool"],["days_ahead","الحجز قبلها بكام يوم","number"],["weekly_off","يوم الإجازة الأسبوعي","day"],["max_queue_per_period","أقصى زباين في الفترة لكل حلاق","number"]],
staff:[["default_commission","عمولة الحلاق الجديد (افتراضي) %","number"],["attendance_radius_m","نطاق تسجيل الحضور بالمتر","number"],["salon_lat","خط عرض الصالون","number"],["salon_lng","خط طول الصالون","number"]],
pos:[["max_discount_pct","أقصى خصم للكاشير %","number"]],
stock:[["low_stock_default","الحد الأدنى الافتراضي للمنتج الجديد","number"]],
loy:[["points_per_currency","كل كام جنيه = نقطة ولاء","number"],["welcome_bonus","هدية التسجيل (نقاط)","number"],["review_bonus","نقاط التقييم","number"],["visit_bonus_every","مكافأة كل كام زيارة","number"],["visit_bonus_points","نقاط مكافأة الزيارات","number"],["tier_silver","نقاط المستوى الفضي (إجمالي)","number"],["tier_gold","نقاط المستوى الذهبي","number"],["tier_vip","نقاط مستوى VIP","number"]]};
const RST={book:[["queue","تصفير الدور الحالي (مسح كل الحجوزات غير المنتهية)"],["appointments","مسح كل الحجوزات وتقييماتها"]],staff:[["attendance","تصفير سجل الحضور"],["staff_tx","تصفير السحب والخصومات والمكافآت"]],pos:[["invoices","مسح كل الفواتير"]],stock:[["stock","تصفير كميات المخزون وحركاته"]],loy:[["loyalty","تصفير نقاط وكوبونات كل العملاء"]],danger:[["reviews","مسح كل التقييمات"],["expenses","مسح كل المصروفات"],["customers","مسح كل العملاء وبياناتهم"],["all","تصفير كل البيانات (فواتير، حجوزات، عملاء، حضور، مخزون، نقاط، مصروفات)"]]};
async function copyBook(){const u=location.origin+"/book";try{await navigator.clipboard.writeText(u);toast("تم نسخ الرابط ✓")}catch(e){prompt("انسخ الرابط:",u)}}
V.set=async()=>{await loadCfg();
const[{data:sv},{data:pr},{data:rw}]=await Promise.all([sb.from("services").select("*").order("id"),sb.from("products").select("*").order("id"),sb.from("loyalty_rewards").select("*").order("cost")]);C.cat={services:sv,products:pr};
const sec=C.sec||"general",c=C.cfg;
const fld=([k,l,t])=>t=="bool"?`<label class="row" style="cursor:pointer"><span>${l}</span><input type="checkbox" id="s_${k}" ${c[k]?"checked":""} style="width:22px;height:22px;margin:0"></label>`:t=="day"?`<label class="m">${l}</label><select id="s_${k}">${DAYS7.map((d,i)=>`<option value="${i}" ${c[k]==i?"selected":""}>${d}</option>`).join("")}<option value="-1" ${c[k]==-1?"selected":""}>مفيش إجازة</option></select>`:`<label class="m">${l}</label><input id="s_${k}" type="${t||"text"}" step="any" value="${esc(c[k])}">`;
let h=`<h1>الإعدادات</h1><div class="chips">${SEC.map(x=>`<button class="chip ${sec==x[0]?"sel":""}" onclick="C.sec='${x[0]}';V.set()">${x[1]}</button>`).join("")}</div>`;
if(FLD[sec])h+=`<div class="box">${FLD[sec].map(fld).join("")}${sec=="staff"?`<button class="btn g s" style="margin-bottom:8px" onclick="setHere()">📍 استخدم موقعي الحالي (وانت في الصالون)</button>`:""}<button class="btn" style="width:100%" onclick="saveSec()">حفظ</button></div>`;
const row=(t,x,d)=>`<div class="row"><div><b>${esc(x.name)}</b><div class="m">${d}${x.active?"":" · موقوف"}</div></div><div><button class="btn s g" onclick="editItem('${t}',${x.id})">تعديل</button> <button class="btn s g" onclick="toggleItem('${t}',${x.id},${!x.active})">${x.active?"إيقاف":"تفعيل"}</button></div></div>`;
if(sec=="book")h+=`<h2>صفحة الحجز المستقلة</h2><div class="chips"><a class="btn g s" style="text-decoration:none" href="/qr" target="_blank">🔳 باركود صفحة الحجز</a><button class="btn g s" onclick="copyBook()">نسخ رابط الحجز</button></div><div class="m" style="margin-bottom:6px">العملاء بيحجزوا من الرابط ده من غير تسجيل ولا تطبيق.</div><h2>منيو الخدمات</h2>`+sv.map(x=>row("services",x,`${esc(x.category||"")} · ${x.price} · ${x.duration_min} دقيقة`)).join("")+`<button class="btn g s" onclick="addItem('services')">+ خدمة جديدة</button>`;
if(sec=="stock")h+=`<h2>المنتجات</h2>`+pr.map(x=>row("products",x,`بيع ${x.price} · شراء ${x.cost} · الحد الأدنى ${x.min_stock}`)).join("")+`<button class="btn g s" onclick="addItem('products')">+ منتج جديد</button>`;
if(sec=="loy")h+=`<h2>مكافآت الولاء</h2>`+(rw||[]).map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="m">${x.cost} نقطة ${x.active?"":"· موقوفة"}</div></div><button class="btn s g" onclick="togRw(${x.id},${!x.active})">${x.active?"إيقاف":"تفعيل"}</button></div>`).join("")+`<button class="btn g s" onclick="addRw()">+ مكافأة جديدة</button>`;
if(sec=="staff")h+=`<h2>إدارة الموظفين</h2><div class="chips"><button class="btn g" onclick="go('team')">الموظفين والصلاحيات والشيفتات</button><button class="btn g" onclick="resetAllPerms()">إرجاع صلاحيات الكل للافتراضي</button></div>`;
if(RST[sec])h+=`<h2 style="color:var(--red)">${sec=="danger"?"منطقة الخطر":"تصفير"}</h2>`+RST[sec].map(r=>`<button class="row" style="cursor:pointer;color:var(--red);font-weight:600" onclick="doReset('${r[0]}',this.textContent)">${r[1]}</button>`).join("");
put(h)};
async function saveSec(){const rows=[];(FLD[C.sec]||[]).forEach(([k,l,t])=>{const e=$("s_"+k);if(!e)return;if(t=="bool")rows.push({key:k,value:e.checked});else if(t=="number"||t=="day"){if(e.value!=="")rows.push({key:k,value:+e.value})}else rows.push({key:k,value:e.value})});
const{error}=await sb.from("app_settings").upsert(rows);error?toast(error.message):(toast("تم الحفظ ✓"),loadCfg())}
async function doReset(scope,label){const w=prompt(label+"\n\nالعملية دي مش هتترجّع. اكتب كلمة: تصفير");if(w!=="تصفير")return toast("اتلغى");const{data,error}=await sb.rpc("reset_data",{p_scope:scope,p_confirm:w});error?toast(error.message):toast(data||"تم التصفير ✓")}
async function resetAllPerms(){if(!confirm("ترجّع صلاحيات كل الحلاقين والكاشير للافتراضي؟"))return;const{error}=await sb.from("profiles").update({perms:{}}).in("role",["barber","cashier","assistant"]);error?toast(error.message):toast("تم ✓")}
// ================= العملاء =================
V.cust=async()=>{const{data}=await sb.rpc("customers_overview");C.CU=data||[];C.cq="";
put(`<h1>العملاء</h1>${can("use_pos")?`<button class="btn s" onclick="addCustForm()">+ إضافة عميل</button><div id="ac"></div>`:""}<input placeholder="ابحث بالاسم أو الموبايل" oninput="C.cq=this.value;$('cl').innerHTML=custRows()"><div id="cl">${custRows()}</div>`)};
function addCustForm(){const e=$("ac");if(e.innerHTML)return e.innerHTML="";e.innerHTML=`<div class="box" style="margin:10px 0"><input id="ac_n" placeholder="اسم العميل"><input id="ac_p" type="tel" inputmode="numeric" placeholder="رقم الموبايل (01xxxxxxxxx)"><div class="chips"><button class="btn" onclick="saveCust()">حفظ العميل</button><button class="btn g" onclick="$('ac').innerHTML=''">إلغاء</button></div></div>`;$("ac_n").focus()}
async function saveCust(){const n=$("ac_n").value.trim(),ph=$("ac_p").value.replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d)).replace(/\D/g,"");
if(n.length<2)return toast("اكتب اسم العميل");if(!/^01\d{9}$/.test(ph))return toast("الموبايل لازم 11 رقم ويبدأ بـ 01");
const{error}=await sb.rpc("add_customer",{p_name:n,p_phone:ph});error?toast(error.message):(toast("تمت إضافة "+n+" ✓"),V.cust())}
const custRows=()=>{const q=(C.cq||"").trim(),L=C.CU.filter(x=>!q||x.name.includes(q)||(x.phone||"").includes(q));return `<div class="m" style="margin-bottom:8px">${L.length} عميل</div>`+L.map(x=>`<button class="row" style="cursor:pointer" onclick="openCust(${x.id})"><div><b>${esc(x.name)}</b><div class="m">${esc(x.phone||"")} · ${x.visits} زيارة · دفع ${fm(x.spent)}</div></div><span class="tag" style="background:var(--brass);color:#fff">${x.points} نقطة</span></button>`).join("")};
async function openCust(id){const x=C.CU.find(y=>y.id==id);const{data}=await sb.from("invoices").select("no,total,created_at,payment_method,invoice_items(name,qty)").eq("customer_id",id).order("created_at",{ascending:false}).limit(15);
put(`<button class="btn g s" style="margin-top:12px" onclick="V.cust()">‹ رجوع</button><h1>${esc(x.name)}</h1><div class="box"><div>${esc(x.phone||"")}</div><div class="m">انضم ${new Date(x.joined).toLocaleDateString("ar-EG")} · آخر زيارة ${x.last_visit?new Date(x.last_visit).toLocaleDateString("ar-EG"):"—"}</div><div class="m">${x.visits} زيارة · إجمالي ${fm(x.spent)} · ${x.points} نقطة (إجمالي ${x.lifetime_points})</div></div>${me.role=="owner"?`<div class="chips" style="margin-top:8px"><button class="btn s" onclick="adjP(${id})">تعديل النقاط</button><button class="btn s g" style="color:var(--red)" onclick="delC(${id})">حذف العميل</button></div>`:""}<h2>آخر الفواتير</h2>`+((data||[]).length?data.map(i=>`<div class="row"><div><b>#${i.no}</b> · ${new Date(i.created_at).toLocaleDateString("ar-EG")}<div class="m">${i.invoice_items.map(z=>esc(z.name)+(z.qty>1?" ×"+z.qty:"")).join(" + ")}</div></div><b>${fm(i.total)}</b></div>`).join(""):`<p class="m">مفيش فواتير.</p>`))}
async function adjP(id){const n=+prompt("عدد النقاط (موجب للإضافة، سالب للخصم)");if(!n)return;const note=prompt("السبب","تعديل إداري")||"";const{error}=await sb.rpc("adjust_points",{p_customer:id,p_pts:n,p_note:note});error?toast(error.message):(toast("تم ✓"),V.cust())}
async function delC(id){if(!confirm("حذف العميل وكل حجوزاته وتقييماته؟ مش هيترجّع."))return;const{error}=await sb.rpc("delete_customer",{p_id:id});error?toast(error.message):(toast("تم الحذف"),V.cust())}
// ================= التقارير =================
const num=x=>Math.round(+x||0).toLocaleString("ar-EG"),ymd=d=>d.toLocaleDateString("en-CA");
const tbl=(h,rows)=>rows.length?`<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px"><tr>${h.map(x=>`<th style="text-align:right;padding:6px;border-bottom:1px solid var(--line);color:var(--mute);white-space:nowrap">${x}</th>`).join("")}</tr>${rows.map(r=>`<tr>${r.map(c=>`<td style="padding:6px;border-bottom:1px dashed var(--line)">${c}</td>`).join("")}</tr>`).join("")}</table></div>`:`<p class="m">مفيش بيانات في الفترة دي.</p>`;
const bars=(a,lab,val)=>{const m=Math.max(1,...a.map(val));return a.length?a.map(x=>`<div style="margin-bottom:7px"><div style="display:flex;justify-content:space-between;font-size:12px"><span>${lab(x)}</span><b>${fm(val(x))}</b></div><div style="height:8px;border-radius:6px;background:var(--line);overflow:hidden"><i style="display:block;height:100%;width:${val(x)/m*100}%;background:var(--blue)"></i></div></div>`).join(""):`<p class="m">مفيش بيانات.</p>`};
const kc=(l,v,c)=>`<div class="box" style="text-align:center"><div class="m">${l}</div><div style="font-weight:800;font-size:18px;color:${c||"inherit"}">${v}</div></div>`;
const RSEC=[["sum","الملخص"],["sales","المبيعات"],["staff","الموظفين"],["cust","العملاء"],["queue","الدور والتقييم"],["stock","المخزون"],["exp","المصروفات"]];
function rangeR(k){const a=new Date();a.setHours(0,0,0,0);const b=new Date(a);b.setDate(b.getDate()+1);const t=new Date();
if(k=="yesterday"){a.setDate(a.getDate()-1);b.setDate(b.getDate()-1)}else if(k=="week")a.setDate(a.getDate()-6);else if(k=="month")a.setDate(1);
else if(k=="lastmonth"){a.setFullYear(t.getFullYear(),t.getMonth()-1,1);b.setFullYear(t.getFullYear(),t.getMonth(),1)}
else if(k=="custom"&&C.rf&&C.rt){const x=new Date(C.rf+"T00:00"),y=new Date(C.rt+"T00:00");y.setDate(y.getDate()+1);return[x,y]}
return[a,b]}
V.rep=async()=>{C.rk=C.rk||"month";C.rs=C.rs||"sum";repLoad()};
async function repLoad(){const[a,b]=rangeR(C.rk);const[{data,error},{data:ex}]=await Promise.all([sb.rpc("report_data",{p_from:a.toISOString(),p_to:b.toISOString()}),sb.from("expenses").select("*").gte("spent_on",ymd(a)).lt("spent_on",ymd(b)).order("spent_on",{ascending:false})]);
if(error)return put(`<h1>التقارير</h1><p class="m">${esc(error.message)}</p>`);C.rd=data;C.rx=ex||[];C.rr=[a,b];drawRep()}
function drawRep(){const d=C.rd,T=d.totals,[a,b]=C.rr,e=new Date(b);e.setDate(e.getDate()-1);
const RK=[["today","اليوم"],["yesterday","أمس"],["week","7 أيام"],["month","الشهر"],["lastmonth","الشهر اللي فات"],["custom","مخصص"]];
let h=`<h1>التقارير</h1><div class="chips">${RK.map(x=>`<button class="chip ${C.rk==x[0]?"sel":""}" onclick="C.rk='${x[0]}';repLoad()">${x[1]}</button>`).join("")}</div>${C.rk=="custom"?`<div class="chips" style="align-items:center"><input type="date" id="rf" value="${C.rf||ymd(a)}" style="width:auto;margin:0"><span class="m">إلى</span><input type="date" id="rt" value="${C.rt||ymd(e)}" style="width:auto;margin:0"><button class="btn s" onclick="C.rf=$('rf').value;C.rt=$('rt').value;repLoad()">عرض</button></div>`:""}<div class="m" style="margin-bottom:6px">${ymd(a)} ← ${ymd(e)}</div><div class="chips">${RSEC.map(x=>`<button class="chip ${C.rs==x[0]?"sel":""}" onclick="C.rs='${x[0]}';drawRep()">${x[1]}</button>`).join("")}</div>`;
const s=C.rs;
if(s=="sum")h+=`<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">${kc("المبيعات",fm(T.revenue))}${kc("صافي الربح",fm(T.profit),T.profit>=0?"var(--ok)":"var(--red)")}${kc("عدد الفواتير",num(T.invoices))}${kc("متوسط الفاتورة",fm(T.avg))}${kc("الخصومات",fm(T.discounts))}${kc("المصروفات",fm(T.expenses))}</div>
<h2>إزاي طلع الربح؟</h2><div class="box">${[["المبيعات",T.revenue,1],["تكلفة المنتجات المباعة",-T.cogs],["عمولات الحلاقين (بعد خصم المساعدين)",-T.commissions],["رواتب المساعدين",-(T.salaries||0)],["المكافآت",-T.bonuses],["الخصومات على الموظفين",T.deductions],["المصروفات",-T.expenses],["صافي الربح",T.profit,1]].map(r=>`<div class="tot" style="display:flex;justify-content:space-between;padding:4px 0;${r[2]?"font-weight:800":""}"><span>${r[0]}</span><span>${fm(r[1])}</span></div>`).join("")}</div><div class="m" style="margin-top:6px">سحب الموظفين في الفترة: ${fm(T.advances)} (بتتخصم من مستحقاتهم ومش مصروف)</div>${T.assistant_cuts?`<div class="m">حصة المحل من خدمات المساعدين في الفترة: ${fm(T.assistant_cuts)} (متحسوبة جوه المبيعات ومخصومة من عمولات الحلاقين)</div>`:""}
<h2>المبيعات يوم بيوم</h2>${bars(d.by_day,x=>x.d,x=>x.t)}`;
if(s=="sales")h+=`<h2>طرق الدفع</h2>${tbl(["الطريقة","الفواتير","الإجمالي"],d.by_pay.map(x=>[{cash:"كاش",card:"كارت",wallet:"محفظة"}[x.m]||x.m,x.n,fm(x.t)]))}<h2>الخدمات</h2>${tbl(["الخدمة","العدد","الإيراد"],d.services.map(x=>[esc(x.n),x.q,fm(x.t)]))}<h2>المنتجات</h2>${tbl(["المنتج","العدد","الإيراد","الربح"],d.products.map(x=>[esc(x.n),x.q,fm(x.t),fm(x.p)]))}<h2>ساعات الذروة</h2>${bars(d.by_hour,x=>x.h+":00",x=>x.t)}`;
if(s=="staff")h+=`<h2>أداء الحلاقين</h2>${tbl(["الحلاق","الزباين","المبيعات","العمولة","التقييم"],d.barbers.map(x=>[esc(x.n),x.cuts,fm(x.sales),fm(x.comm),x.rating?"★ "+x.rating:"—"]))}${(d.assistants||[]).length?`<h2>المساعدين</h2>${tbl(["المساعد","خدمات","قيمتها","حصة المحل","راتب الفترة"],d.assistants.map(x=>[esc(x.n),x.svc,fm(x.val),fm(x.cut),fm(x.sal)]))}`:""}<h2>الحضور</h2>${tbl(["الموظف","أيام","ساعات","تأخير (د)"],d.attendance.map(x=>[esc(x.n),x.days,x.hrs,x.late]))}<h2>حركات الموظفين</h2><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px">${kc("مكافآت",fm(T.bonuses),"var(--ok)")}${kc("سحب",fm(T.advances),"var(--red)")}${kc("خصومات",fm(T.deductions),"var(--red)")}</div>`;
if(s=="cust")h+=`<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px">${kc("كل العملاء",num(d.customers.total))}${kc("جدد",num(d.customers.new))}${kc("نشطين",num(d.customers.active))}</div><h2>أعلى العملاء إنفاقًا</h2>${tbl(["العميل","الموبايل","الزيارات","الإنفاق"],d.customers.top.map(x=>[esc(x.n),esc(x.ph||""),x.v,fm(x.t)]))}<h2>الولاء</h2><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">${kc("نقاط ممنوحة",num(d.loyalty.issued))}${kc("نقاط مستبدلة",num(d.loyalty.redeemed))}${kc("كوبونات مفعّلة",num(d.loyalty.active))}${kc("كوبونات اتستخدمت",num(d.loyalty.used))}</div>`;
if(s=="queue"){const tot=d.tickets.reduce((a,x)=>a+x.n,0),can2=(d.tickets.find(x=>x.s=="cancelled")||{n:0}).n;h+=`<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">${kc("إجمالي الحجوزات",num(tot))}${kc("نسبة الإلغاء",(tot?Math.round(can2/tot*100):0)+"%")}</div><h2>حالات الحجز</h2>${tbl(["الحالة","العدد"],d.tickets.map(x=>[ST[x.s]||x.s,x.n]))}<h2>الفترات</h2>${tbl(["الفترة","الحجوزات"],d.periods.map(x=>[PLB[x.p]||x.p,x.n]))}<h2>التقييمات (${d.ratings.n})</h2><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px">${kc("الحلاق",d.ratings.barber?"★ "+d.ratings.barber:"—")}${kc("الخدمة",d.ratings.service?"★ "+d.ratings.service:"—")}${kc("المكان",d.ratings.place?"★ "+d.ratings.place:"—")}</div>`}
if(s=="stock")h+=`<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">${kc("قيمة المخزون (تكلفة)",fm(d.stock.cost_value))}${kc("قيمة المخزون (بيع)",fm(d.stock.retail_value))}</div><h2>نواقص المخزون</h2>${tbl(["المنتج","الكمية","الحد الأدنى"],d.stock.low.map(x=>[esc(x.n),x.q,x.min]))}`;
if(s=="exp")h+=`<h2>إضافة مصروف</h2><div class="box"><select id="xc">${["إيجار","كهرباء ومياه","رواتب","مشتريات","صيانة","تسويق","أخرى"].map(c=>`<option>${c}</option>`).join("")}</select><input id="xa" type="number" inputmode="decimal" placeholder="المبلغ"><input id="xn" placeholder="ملاحظة (اختياري)"><input id="xd" type="date" value="${ymd(new Date())}">${me.role=="owner"?`<button class="btn" onclick="addExp()">حفظ المصروف</button>`:""}</div><h2>حسب البند</h2>${tbl(["البند","الإجمالي"],d.expenses.map(x=>[esc(x.c),fm(x.t)]))}<h2>المصروفات</h2>`+(C.rx.length?C.rx.map(x=>`<div class="row"><div><b>${esc(x.category)}</b> · ${fm(x.amount)}<div class="m">${x.spent_on} ${esc(x.note||"")}</div></div>${me.role=="owner"?`<button class="btn s g" onclick="delExp(${x.id})">حذف</button>`:""}</div>`).join(""):`<p class="m">مفيش مصروفات.</p>`);
h+=`<div class="chips" style="margin-top:16px"><button class="btn g s" onclick="exportCsv()">⬇ تصدير الفواتير (CSV)</button><button class="btn g s" onclick="print()">🖨 طباعة</button></div>`;put(h)}
async function addExp(){const a=+$("xa").value;if(!(a>0))return toast("اكتب المبلغ");const{error}=await sb.from("expenses").insert({category:$("xc").value,amount:a,note:$("xn").value,spent_on:$("xd").value});error?toast(error.message):(toast("تم ✓"),repLoad())}
async function delExp(id){if(!confirm("حذف المصروف؟"))return;await sb.from("expenses").delete().eq("id",id);repLoad()}
async function exportCsv(){const[a,b]=C.rr;const{data}=await sb.from("invoices").select("no,created_at,total,discount,payment_method,customers(name),profiles:barber_id(full_name),invoice_items(name,qty)").gte("created_at",a.toISOString()).lt("created_at",b.toISOString()).order("created_at");
const q=v=>'"'+String(v??"").replace(/"/g,'""')+'"';const rows=[["رقم","التاريخ","العميل","الحلاق","البنود","الخصم","الإجمالي","الدفع"],...(data||[]).map(i=>[i.no,new Date(i.created_at).toLocaleString("ar-EG"),i.customers?.name||"عابر",i.profiles?.full_name||"",i.invoice_items.map(z=>z.name+" x"+z.qty).join(" + "),i.discount,i.total,i.payment_method])];
const blob=new Blob(["\ufeff"+rows.map(r=>r.map(q).join(",")).join("\n")],{type:"text/csv;charset=utf-8"}),u=URL.createObjectURL(blob),l=document.createElement("a");l.href=u;l.download="invoices-"+ymd(a)+".csv";l.click();URL.revokeObjectURL(u)}

// ================= PWA: تثبيت التطبيق =================
if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("/sw.js").catch(()=>{}));
let dip=null;const standalone=()=>matchMedia("(display-mode: standalone)").matches||navigator.standalone;
function instBanner(msg,btn){if(standalone()||$("inst"))return;try{if(localStorage.getItem("inst_x"))return}catch(e){}
const d=document.createElement("div");d.id="inst";d.className="inst";
d.innerHTML=`<span style="flex:1">${msg}</span>${btn?`<button class="btn s" id="instb">تثبيت</button>`:""}<button aria-label="إغلاق" id="instx" style="background:none;border:0;color:inherit;font-size:22px;cursor:pointer">×</button>`;document.body.appendChild(d);
$("instx").onclick=()=>{d.remove();try{localStorage.setItem("inst_x","1")}catch(e){}};
if(btn)$("instb").onclick=async()=>{dip.prompt();await dip.userChoice;dip=null;d.remove()}}
addEventListener("beforeinstallprompt",e=>{e.preventDefault();dip=e;instBanner("ثبّت التطبيق على موبايلك للدخول السريع",true)});
addEventListener("appinstalled",()=>{$("inst")?.remove()});
if(/iphone|ipad|ipod/i.test(navigator.userAgent)&&!standalone())setTimeout(()=>instBanner("لتثبيت التطبيق: اضغط زر المشاركة ثم «إضافة إلى الشاشة الرئيسية»",false),2500);
addEventListener("offline",()=>toast("مفيش إنترنت"));addEventListener("online",()=>toast("رجع الإنترنت ✓"));

// ================= هوية فاخرة: أيقونات + شاشات =================
const IC={
pos:'<path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1Z"/><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"/><path d="M12 17.5v-11"/>',
appts:'<path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z"/><path d="M13 5v2"/><path d="M13 17v2"/><path d="M13 11v2"/>',
stock:'<path d="m7.5 4.27 9 5.15"/><path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/>',
inv:'<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>',
cust:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
rep:'<path d="M3 3v18h18"/><path d="M18 17V9"/><path d="M13 17V5"/><path d="M8 17v-3"/>',
me:'<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
set:'<path d="M21 4h-7"/><path d="M10 4H3"/><path d="M21 12h-9"/><path d="M8 12H3"/><path d="M21 20h-5"/><path d="M12 20H3"/><path d="M14 2v4"/><path d="M8 10v4"/><path d="M16 18v4"/>',
out:'<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="m16 17 5-5-5-5"/><path d="M21 12H9"/>',
book:'<path d="M8 2v4"/><path d="M16 2v4"/><path d="M21 13V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h8"/><path d="M3 10h18"/><path d="M19 16v6"/><path d="M16 19h6"/>',
mine:'<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>',
loy:'<path d="M6 3h12l4 6-10 13L2 9Z"/><path d="M11 3 8 9l4 13 4-13-3-6"/><path d="M2 9h20"/>',
menu:'<circle cx="6" cy="6" r="3"/><path d="M8.12 8.12 12 12"/><path d="M20 4 8.12 15.88"/><circle cx="6" cy="18" r="3"/><path d="M14.8 14.8 20 20"/>',
dot:'<circle cx="12" cy="12" r="3"/>'};
IC.queue=IC.appts;IC.team=IC.cust;
const ic=k=>`<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${IC[k]||IC.dot}</svg>`;
const SK='<div class="sk" style="height:30px;width:52%"></div><div class="sk" style="height:130px"></div><div class="sk" style="height:70px"></div><div class="sk" style="height:70px"></div>';
function authView(){put(`<div class="hero"><div class="emblem">${ic("menu")}</div><h1>${esc(C.cfg.salon_name)}</h1><div class="tagline">${APP_MODE=="staff"?"لوحة الموظفين والإدارة":"حجز بدون انتظار · نقاط ولاء · تجربة راقية"}</div></div>`+(APP_MODE=="staff"?`<div class="box"><input id="em" placeholder="كود الموظف (أو البريد للمالك)" autocomplete="username"><input id="pw" type="password" placeholder="كلمة السر" autocomplete="current-password"><button class="btn" style="width:100%" onclick="login()">دخول</button></div>`:`<div class="box"><input id="cn" placeholder="اسمك"><input id="cp" type="tel" inputmode="numeric" placeholder="رقم موبايلك (01xxxxxxxxx)"><button class="btn" style="width:100%" onclick="regCustomer()">ابدأ</button><p class="m" style="text-align:center;margin:12px 0 0">سجّل مرة واحدة بس، وهتدخل على حسابك علطول</p></div>`))}
function drawQ(s){C.qid=s.id;const st=s.status,steps=[["مستني دورك",1],["اتنادى عليك",s.called||st!="upcoming"],["وصلت الصالون",st=="checked_in"||st=="in_service"],["بدأت الخدمة",st=="in_service"],["خلصت — ادفع عند الكاشير",s.finished]];
let cur=-1;steps.forEach((x,i)=>{if(x[1])cur=i});
put(`<div class="hello">دورك مع ${esc(s.barber_name)}</div><h1>دوري</h1>
<div class="pass"><div class="pass-top"><div class="m">رقم دورك</div><div class="pass-no">${s.ticket_no}</div><div class="m">${PLB[s.period]} · ${s.day}</div></div><div class="perf"></div>
<div class="pass-bot"><div><div class="m">بيحلق دلوقتي</div><b class="big2">${s.current_no?"#"+s.current_no:"—"}</b></div><div><div class="m">قدامك</div><b class="big2">${s.ahead}</b></div><div><div class="m">الوقت المتوقع</div><b class="big2">~${s.est_min}<small> د</small></b></div></div></div>
<div class="row" style="margin-top:14px"><span>${esc(s.services)}</span><b style="color:var(--gold2);font-family:var(--display);font-size:20px">${fm(s.total)}</b></div>
${s.called&&st=="upcoming"?`<div class="callbox"><b>اتنادى عليك</b><div class="m" style="margin:2px 0 10px">قولنا إنت فين</div><div class="chips" style="margin:0"><button class="btn" ${s.eta=="on_way"?"disabled":""} onclick="eta('on_way')">أنا في الطريق</button><button class="btn" style="background:linear-gradient(180deg,#52C08C,#2E8B5E);color:#fff" onclick="eta('arrived')">وصلت</button></div></div>`:""}
<ul class="tl">${steps.map((x,i)=>`<li class="${x[1]?(i==cur?"now":"done"):""}">${x[0]}</li>`).join("")}</ul>
${!s.called&&st=="upcoming"?`<button class="btn g" style="width:100%" onclick="cancelT()">إلغاء الحجز</button>`:""}`)}
V.loy=async()=>{const{data:{user}}=await sb.auth.getUser();const{data:c}=await sb.from("customers").select("id,name,phone,points,lifetime_points,visits").eq("user_id",user.id).single();
const[{data:tr},{data:rw},{data:vo},{data:lg}]=await Promise.all([sb.rpc("loyalty_tier",{p_life:c.lifetime_points}),sb.from("loyalty_rewards").select("*").eq("active",true).order("cost"),sb.from("loyalty_redemptions").select("code,loyalty_rewards(name)").eq("customer_id",c.id).eq("status","active"),sb.from("loyalty_ledger").select("*").eq("customer_id",c.id).order("created_at",{ascending:false}).limit(15)]);
const t=tr[0],pct=t.next_at?Math.min(100,c.lifetime_points/t.next_at*100):100,g=C.cfg;
put(`<div class="vip"><div class="vip-top"><span class="vip-brand">${esc(g.salon_name)}</span><span class="vip-tier">${t.name}${t.mult>1?" · ×"+t.mult:""}</span></div><div class="vip-pts">${num(c.points)}<small>نقطة</small></div><div class="vip-bar"><i style="width:${pct}%"></i></div><div class="vip-foot"><span>${t.next_at?"باقي "+num(t.next_at-c.lifetime_points)+" نقطة للمستوى الجاي":"وصلت لأعلى مستوى"}</span><span>${esc(c.name)} · ${esc((c.phone||"").slice(-4))}</span></div></div>
${vo?.length?`<h2>كوبوناتك — قدّم الكود للكاشير</h2>`+vo.map(v=>`<div class="row"><span>${esc(v.loyalty_rewards.name)}</span><b style="font-family:var(--display);font-size:24px;letter-spacing:3px;color:var(--gold2)">${v.code}</b></div>`).join(""):""}
<h2>استبدل نقاطك</h2>`+(rw||[]).map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="m">${x.cost} نقطة</div></div><button class="btn s" ${c.points<x.cost?"disabled":""} onclick="redeem(${x.id})">استبدل</button></div>`).join("")+`<h2>إزاي تكسب نقاط؟</h2><div class="box m" style="line-height:2">كل ${g.points_per_currency} ${g.currency} = نقطة (× مستواك)<br>${g.review_bonus} نقطة على كل تقييم<br>${g.visit_bonus_points} نقطة كل ${g.visit_bonus_every} زيارات<br>${g.welcome_bonus} نقطة هدية التسجيل</div><h2>آخر الحركات</h2>`+((lg||[]).length?lg.map(l=>`<div class="row"><div>${RSN[l.reason]||l.reason}<div class="m">${new Date(l.created_at).toLocaleDateString("ar-EG")}</div></div><b style="color:${l.points>0?"var(--ok)":"var(--red)"}">${l.points>0?"+":""}${l.points}</b></div>`).join(""):`<p class="m">لسه مفيش حركات.</p>`))};

boot();
